### ISSUE TITLE
Error while building Dependencies in v0.2.0

### ISSUE THREAD

**Issue by Giom-fm** [strukturag/nextcloud-spreed-signaling#122]
I am trying to build version 0.2.0 as I assume this is the last stable version. Unfortunately the process fails already when building the dependencies.

go version go1.16.4 linux/amd64

`/usr/bin/go build -o ./vendor/bin/easyjson ./vendor/src/github.com/mailru/easyjson/easyjson/main.go
vendor/src/github.com/mailru/easyjson/easyjson/main.go:11:2: no required module provides package github.com/mailru/easyjson/bootstrap: go.mod file not found in current directory or any parent directory; see 'go help modules'
vendor/src/github.com/mailru/easyjson/easyjson/main.go:15:2: no required module provides package github.com/mailru/easyjson/gen: go.mod file not found in current directory or any parent directory; see 'go help modules'
vendor/src/github.com/mailru/easyjson/easyjson/main.go:16:2: no required module provides package github.com/mailru/easyjson/parser: go.mod file not found in current directory or any parent directory; see 'go help modules'`

Edit: if I build the latest state of master branch everything works fine.

**Comment by fancycode** [comment]
Does the current master work for you?

**Comment by Giom-fm** [comment]
Thanks for the reply.

As I mentioned, the latest version works on the master branch. I don't see any changes in the meantime. However, it seems to me that this is your development branch. If this is the case I would not like to use it in production.

**Comment by fancycode** [comment]
Version 0.3.0 has been released:
https://github.com/strukturag/nextcloud-spreed-signaling/releases/tag/v0.3.0
