### ISSUE TITLE
Received unsupported content-type

### ISSUE THREAD

**Issue by acsfer** [strukturag/nextcloud-spreed-signaling#123]
Signaling server is logging plenty of:

> backend_client.go:345: Received unsupported content-type from https://example.com/ocs/v2.php/apps/spreed/api/v1/signaling/backend: text/html; charset=UTF-8 (200 OK)

In the Talk frontend, we're getting:

> Failed to establish signaling connection. Something might be wrong in the signaling server configuration

In the browser console:

![image](https://user-images.githubusercontent.com/12234510/121885565-9a7f3500-cd14-11eb-9ab3-7f19d4860273.png)

But in the configuration settings, everything goes fine:

> OK: Running version:  f38ebdc5181c9985850b4995fdd15c7e43391924

**Comment by fancycode** [comment]
Did you check the `error` object from the browser console for additional information? Are there errors logged in your `nextcloud.log`? Please also double-check that the configured shared secret matches between your Nextcloud settings and the signaling server.

**Comment by acsfer** [comment]
There is nothing in the Nextcloud logs, but we've added the SSL to mySQL requirement to Nextcloud config:

```
'dbdriveroptions' => array(
  \PDO::MYSQL_ATTR_SSL_KEY => '/etc/ssl/mysql/client-key.pem',
  \PDO::MYSQL_ATTR_SSL_CERT => '/etc/ssl/mysql/client-cert.pem',
  \PDO::MYSQL_ATTR_SSL_CA => '/etc/ssl/mysql/ca.pem',
  \PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
),
```

Could this be the reason?

**Comment by acsfer** [comment]
I think problem was more realted to https://github.com/nextcloud/spreed/issues/5148
After add locking support, i can join.

Closing for now, will reopen with more details if needed.

**Comment by acsfer** [comment]
Well it's defenitely MySQL related.
While using SSL options:

```
'dbdriveroptions' => array(
  \PDO::MYSQL_ATTR_SSL_KEY => '/etc/ssl/mysql/client-key.pem',
  \PDO::MYSQL_ATTR_SSL_CERT => '/etc/ssl/mysql/client-cert.pem',
  \PDO::MYSQL_ATTR_SSL_CA => '/etc/ssl/mysql/ca.pem',
  \PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
),
```

but

`ALTER USER 'nextcloud'@'%' REQUIRE NONE;`
so SSL is used but it's NOT mandatory, NO errors. But if I set :

`ALTER USER 'nextcloud'@'%' REQUIRE SSL;`
so SSL is uses and IT'S mandatory, errors again. Can you point me out if this is more a Talk app issue or Signaling?

**Comment by fancycode** [comment]
The signaling server only connects to public endpoints of Talk and doesn't use the database directly. So if the behaviour changes with different MySQL settings, I would assume it's an issue in Talk / Nextcloud.

**Comment by timololipop** [comment]
I am receiving the same error. Was there any activity on this?
