### ISSUE TITLE
Force HTTPS connections to Nextcloud instance

### ISSUE THREAD

**Issue by LukasReschke** [strukturag/nextcloud-spreed-signaling#130]
Right now a user could force a downgrade by setting a HTTP URL directly inside the `hello` message. To avoid any potential sensitive data being transmitted unencrypted we should consider always using HTTPS. (or requiring users to also configure the protocol for any given backend)

**Comment by fancycode** [comment]
This actually already works: if you configure the Nextcloud backend URL with `https`, any connections that try to send a `http` url in the `hello` request will be rejected:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/ed8c2752cb61345e28646be093533f8ad1d373df/server.conf.in#L79

Forcing HTTPS however is a good idea for the old-style configuration where only the hostname was configured.
