### ISSUE TITLE
Which port should public reachable and which one only from nextcloud instance?

### ISSUE THREAD

**Issue by christiansicari** [strukturag/nextcloud-spreed-signaling#136]
janus: WebRTC gateway used by spreedbackend. WebRTC port range (20000-20100/udp) exposed to public.
nginx: Reverse proxy for spreedbackend. HTTP(S) exposed to public.
nats: NATS streaming server because required by spreedbackend.
coturn TURN relay. Ports 3478,5349 (TCP/UDP) and 49160-49200 (UDP) exposed to public.

I got these port from https://github.com/lnobach/nctalk-backend-cloud-config
But coturn is reached from client? I am not sure about that

**Comment by fancycode** [comment]
coturn is used by the clients to find out the external ip address if behind a NAT / firewall (STUN) or to relay the media streams if direct connections are not possible (TURN).

**Comment by francoisPE** [comment]
Sorry for reopening that topic.
I face firewall issues on my signaling configuration.
Would you please confirm that it is needed to open : 20000-20100/udp and 3478,5349 (TCP/UDP) and 49160-49200 (UDP) ?
Is there any other ports opening required ?
