### ISSUE TITLE
Problem with compiling. invalid pseudo-version, fatal: git fetch-pack: expected shallow list

### ISSUE THREAD

**Issue by gecegezen** [strukturag/nextcloud-spreed-signaling#145]
Hello,

Following error is thrown when I do make build:
GOPATH="/root/nextcloud-spreed-signaling.src/vendor:/root/nextcloud-spreed-signaling.src" /usr/bin/go get -u github.com/mailru/easyjson/...
go: go.etcd.io/etcd@v0.5.0-alpha.5.0.20210226220824-aa7126864d82: invalid pseudo-version: git fetch --unshallow -f https://github.com/etcd-io/etcd in /root/nextcloud-spreed-signaling.src/vendor/pkg/mod/cache/vcs/8d0c8c2e7723e01b30c002ed4e74d4605a82294f251ebd67ae6afb9f55368d27: exit status 128:
	fatal: git fetch-pack: expected shallow list
make: *** [vendor/bin/easyjson] Error 1

Could I be missing something? I had compiled previous version without any problem.

**Comment by fancycode** [comment]
Which version of Go is this? The CI is running successfully with Go 1.14 - 1.16.

Did you try deleting your ` vendor`  folder to reset any previous downloads?

**Comment by gecegezen** [comment]
Hi Joachim,
My go version is 1.13.14 linux/amd64, your README.md file notes that go >= 1.13 would be ok. Perhaps I should bump it up? 

I am not adept at intrinsics of go build system. A noob may it be.. The vendor folder you mentioned is the one that is created in the cloned git source when "make build" is executed I guess? Actually, I had started from a clean clone. Anyway, I  tried to remove it, I also tried "make clean". Same thing happens. I also tried to set locale LC_ALL=C; many times it helped me compiling things but unfortunately not this time.

**Comment by fancycode** [comment]
Sorry, this was a typo - CI actually does test with Go 1.13:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/c0603d6b4ddffec9a29c34d66d0e56395c743c27/.github/workflows/test.yml#L16

**Comment by gecegezen** [comment]
I bumped up my go version to 1.15.5 and tried to build a clean clone. This is a CentOS 7 host by the way. My last go update is from epel repos, namely: golang 1.15.5-1.el7

`GOPATH="/root/nextcloud-spreed-signaling.src/vendor:/root/nextcloud-spreed-signaling.src" /usr/bin/go get -u github.com/mailru/easyjson/...
go: github.com/google/uuid@v1.3.0: reading github.com/google/uuid/go.mod at revision v1.3.0: unknown revision v1.3.0
make: *** [vendor/bin/easyjson] Error 1`

It feels like it cannot download its dependecies. I suspected my IP address being blocked for some unknown reason. I tried from my good old gentoo host at home, having go version 1.16.4, it worked. 

I am then leaving this as a note for those who bump their heads to similar problems. 

Thank you for your time. 
All the best.

**Comment by gecegezen** [comment]
### EDIT ###
I was too quick to decide this was because of my IP being blocked. I was misled because of some temporary complication. The real cause is CentOS 7's git version happens to be too old. I downloaded and compiled git from source, and temporarily changed my $PATH to '/root/bin:$PATH' to make system first find my local git binary. And this time signaling server got compiled without hassle.

Problematic CentOS  7 git package is: git.x86_64 / 1.8.3.1-23.el7_8
Also you may want to checkout [this](https://github.com/golang/go/issues/38373) thread about this golang/git problem.
