### ISSUE TITLE
Using it with an already existing Apache server

### ISSUE THREAD

**Issue by Byter3** [strukturag/nextcloud-spreed-signaling#147]
Hi there!
I'm already running an outside facing Apache server. I wnat to install Signaling in an other VM. BUT I can't setup the signaling server to listen not only on 127.0.0.1, but the VM's internal IP as well.

**Comment by kleener** [comment]
In the server.conf.in there is the point #listen = 127.0.0.1:8080.
Theoretically, you could enter any IP there.
Otherwise, I do not yet understand the problem

**Comment by Byter3** [comment]
Solved it finally after starting all over again. Had to put a "*" before the :80 in the signaling VM nginx server conf. Also I only managed to config properly the web facing apache  with a different ddns adress and use it as a virtual server name.
