### ISSUE TITLE
Problems connecting

### ISSUE THREAD

**Issue by jasonjenssen** [strukturag/nextcloud-spreed-signaling#152]
Hello!

I encounter the following issue: I can access the api via https://domain/standalone-signaling/api/v1/welcome, but when I enter it into my nextcloud instance (other server) it says that it cant connect to the server. I double checked the secret.

What could cause this issue?

Thank you for your help!

**Comment by fancycode** [comment]
Can the Nextcloud server connect to the signaling server using this public URL?
