### ISSUE TITLE
JSON parsing seems to have problems

### ISSUE THREAD

**Issue by aviatorhh** [strukturag/nextcloud-spreed-signaling#180]
We have NC 23 and Talk 13.0.1 running with signaling 0.4.0. But there seems to be a problem with the web client. We get:

`signaling[2801]: hub.go:809: Invalid message {Id: Type: Hello:<nil> Bye:<nil> Room:<nil> Message:<nil> Control:<nil> Internal:<nil>} from A.B.C.D: type missing`

in the signaling logs. Running 0.3.0 therefore gives an error message in the NC GUI saying we need to upgrade signaling. Calls do not work either.

**Comment by fancycode** [comment]
A message without a `type` indeed is invalid and this gets ignored. Could you please try rebuilding the signaling server and run `make clean` before doing so? Which version of Go are you using?

**Comment by aviatorhh** [comment]
go version go1.17.5 linux/amd64

I just did a make clean and the problem vanished. I would say for sure I had done it before but now it seems to work. This must be a kind of magic I guess.
Sorry for this confusion.

**Comment by fancycode** [comment]
No problem, glad that it's resolved now. Sometimes the easyjson processor doesn't rebuild the files to parse JSON data properly and only an explicit `make clean` helps.
