### ISSUE TITLE
Receiving HTTP response 405 when using the signaling server

### ISSUE THREAD

**Issue by biggoof1** [strukturag/nextcloud-spreed-signaling#181]
Hi there,

I used the docker-compose version to set up a Nextcloud talk HPB (testing purposes for now). Recreated it right now.
So everything should be up to date.
The /welcome message gets a 200 response (fine :-) . The configuration in the Nextcloud (V23) also gets success messages.
Whenever I want to connect to a chat in the Nextcloud talk app/webfrontend I get a 405 response from the signaling server.
This is a part from the nextcloud log:
"Client error: `POST https://<several addresses and also with localhost>/standalone-signaling/api/v1/room/jipx7b5z` resulted in a `405 Method Not Allowed` response\",\"C

Does anyone know what is going on or how I can find out why it is not working?

Thanks a lot..

Greets,
Christian

**Comment by fancycode** [comment]
Could you please check your webserver logs to see if this really reaches the signaling server? A `POST` to this URL should be handled just fine:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/552eee08123780882322ba9ce0cb82e4fb48ae08/backend_server.go#L154

Any errors during processing of the request inside the signaling server will be answered with a different error than `405 Method Not Allowed`.

**Comment by biggoof1** [comment]
Might have been my setup with central reverse proxy and so..
