### ISSUE TITLE
Error: Server needs to be updated to be compatible with this version of Talk

### ISSUE THREAD

**Issue by rwb99** [strukturag/nextcloud-spreed-signaling#185]
already tried git pull & a reboot a few mins ago so i have the newest signaling code here. im on talk 13.0.1 and nextcloud 32.0.0

**Comment by fancycode** [comment]
Which version of the signaling server is shown in the Talk admin settings?

**Comment by rwb99** [comment]
{"reqId":"xCZDO8L7uGi1t8Jn0fbm","level":3,"time":"2022-01-20T17:40:30+00:00","remoteAddr":"x.x.x.x","user":"x","app":"spreed","method":"DELETE","url":"/ocs/v2.php/apps/spreed/api/v4/room/nntg5zd4/participants/active","message":"Failed to send message to signaling server","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v13.0.0","version":"23.0.0.10","exception":{"Exception":"RuntimeException","Message":"Signaling server needs to be updated to be compatible with this version of Talk","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php","line":141,"function":"doRequest","class":"OCA\\Talk\\Signaling\\BackendNotifier","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php","line":222,"function":"backendRequest","class":"OCA\\Talk\\Signaling\\BackendNotifier","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/Listener.php","line":220,"function":"roomSessionsRemoved","class":"OCA\\Talk\\Signaling\\BackendNotifier","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"OCA\\Talk\\Signaling\\{closure}","class":"OCA\\Talk\\Signaling\\Listener","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Service/ParticipantService.php","line":709,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Controller/RoomController.php","line":1458,"function":"leaveRoomAsSession","class":"OCA\\Talk\\Service\\ParticipantService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"leaveRoom","class":"OCA\\Talk\\Controller\\RoomController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php","Line":90,"CustomMessage":"Failed to send message to signaling server"},"id":"61e9b5b6621e1"}

**Comment by rwb99** [comment]
23.0.0.10? it doesn't say
![image](https://user-images.githubusercontent.com/63825594/150408147-12777ce2-309e-435e-8f53-e8cc4b2f0d6a.png)
ill add ssl to turn later

**Comment by rwb99** [comment]
it says android but it also not working through web
![image](https://user-images.githubusercontent.com/63825594/150408744-593b2267-d8fd-4ce0-b7d9-050f03c48ea3.png)

**Comment by fancycode** [comment]
@nickvergessen: shouldn't the version check work in all cases (even with the required feature flags missing)? Would be helpful to track down which version is currently running.

**Comment by nickvergessen** [comment]
Message printing adjusted in https://github.com/nextcloud/spreed/pull/6839

**Comment by nickvergessen** [comment]
But you could get it from the access.log file?

**Comment by fancycode** [comment]
@rwb99 could you check the version number of the signaling server from the access.log or apply the patch from nextcloud/spreed#6839 to see the version number in the admin settings?

**Comment by rwb99** [comment]
23.0.0.10 is the only version number that shows. I'd rather wait and update through nextcloud to avoid any conflicts. 

 {"reqId":"UelQVFhruvoritm34Kut","level":3,"time":"2022-01-22T02:03:19+00:00","remoteAddr":"xxx","user":"rb99","app":"spreed","method":"DELETE","url":"/ocs/v2.php/apps/spreed/api/v4/room/xxx/participants/active","message":"Failed to send message to signaling server","userAgent":"Mozilla/5.0 (xxx) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.98 Mobile `Safari/537.36","version":"23.0.0.10","exception":{"Exception":"RuntimeException","Message":"Signaling` server needs to be updated to be compatible with this version of Talk","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php","line":141,"function":"doRequest","class":"OCA\\Talk\\Signaling\\BackendNotifier","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php","line":222,"function":"backendRequest","class":"OCA\\Talk\\Signaling\\BackendNotifier","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/Listener.php","line":220,"function":"roomSessionsRemoved","class":"OCA\\Talk\\Signaling\\BackendNotifier","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"OCA\\Talk\\Signaling\\{closure}","class":"OCA\\Talk\\Signaling\\Listener","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Service/ParticipantService.php","line":709,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Controller/RoomController.php","line":1458,"function":"leaveRoomAsSession","class":"OCA\\Talk\\Service\\ParticipantService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"leaveRoom","class":"OCA\\Talk\\Controller\\RoomController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php","Line":90,"CustomMessage":"Failed to send message to signaling server"}}

**Comment by nickvergessen** [comment]
check /var/log/apache2/access.log

**Comment by rwb99** [comment]
![image](https://user-images.githubusercontent.com/63825594/151233694-5cdc1020-784c-4e1e-842a-8d18af6146d8.png)
nginx with php8.0-fpm on ubuntu 20.04

**Comment by rwb99** [comment]
just got it working. i had removed standalone-signaling from nginx location blocks and from HPB url in talk admin settings. 

for whatever reason you cant use "root" blocks in nginx.

error is deceiving as it is the right version just not proxied properly.

![image](https://user-images.githubusercontent.com/63825594/152719318-7d142bcc-ade6-4749-bf08-136b830de049.png)
