### ISSUE TITLE
Program error or my fault? - Screenshot inside

### ISSUE THREAD

**Issue by biggoof1** [strukturag/nextcloud-spreed-signaling#187]
Hi all,

can anyone give me a hint if this is a handling error on my side or if the signaling server (latest version) and nextcloud 23 do not understand each other correctly?
Whenever I want to join a talk chat with an installed and activated high performance backend, I receive an error from the chat but the http communication seems ok to my understanding.
Having a look at the Firefox console reveals an error which I´m not sure if it results from my setup or if there is an error in nextcloud?

With the built in signaling everything works.

Can anyone give me a hint how to dig into more details?
This would be really helpful.
Thank you.
![Console](https://user-images.githubusercontent.com/96337300/150648758-f9133f39-531d-4a28-a1dc-d5b0a4850d3c.jpg)
![Debugger](https://user-images.githubusercontent.com/96337300/150648764-deaa35d2-2969-493a-9408-98e7c16ca977.jpg)
.

**Comment by rwb99** [comment]
Not sure if it's the same as mine #185 it says the error for me in talk admin settings where you put the turn & singaling info

**Comment by biggoof1** [comment]
hmm.. no, this isn´t the same issue..
But I had a message like this with the wrong URL..
Have you tried wss://<your server>/standalone-signaling ?
Without the /standalone-signaling the message you are facing occured..
AND the wss:// solved my issue with the wrong string...
