### ISSUE TITLE
Handle '"all": true' in case of in_call change

### ISSUE THREAD

**Issue by nickvergessen** [strukturag/nextcloud-spreed-signaling#203]
Ref https://github.com/nextcloud/spreed/pull/6948

**Comment by fancycode** [comment]
Currently the signaling server sends a participants update event if the `inCall` flag changed:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/7b631b0b2ac89afbfe6b33f26fb28986510a439b/room.go#L601

This event contains information on all changed sessions as received by Talk:
https://github.com/nextcloud/spreed/blob/610b86b78c987d2bf91fe37b1b99660b8df49f56/lib/Signaling/BackendNotifier.php#L380

This data is not stored yet (e.g. `participantType`), so constructing the event for the `"all": true` case needs more changes. Do you necessarily require all this data or can we omit the list of changed sessions for this case and set a flag `"all": true` in this event, too?

**Comment by nickvergessen** [comment]
You mean this, right?
https://github.com/nextcloud/spreed/blob/79455819db19ae1c01ca5b471441e345a23a53ed/src/utils/signaling.js#L1265-L1278

I guess we can adjust to it. does it come via flags update as its a the call flag being changed?

From what I see web needs adjusting in either case and I guess so do the mobile clients.

**Comment by nickvergessen** [comment]
@fancycode any idea when you would be able to implement this?

**Comment by fancycode** [comment]
My plan is to have something early ready this week.

**Comment by fancycode** [comment]
> My plan is to have something early ready this week.

PR available for testing at https://github.com/strukturag/nextcloud-spreed-signaling/pull/208
