### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by dvzrv** [strukturag/nextcloud-spreed-signaling#21]
Hi! I would like to package this software for Arch Linux (as I already package the [spreed app](https://www.archlinux.org/packages/community/any/nextcloud-app-spreed/)).
[Packaging policies](https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_versioning) currently prevent me from doing this though (because there is no release of this software).

Can you please tag a release? :)

**Comment by fancycode** [comment]
The next release (coming soon) will be properly tagged.

**Comment by dvzrv** [comment]
@fancycode Thanks! That's great news.

Could you close this once the release has been done though? It's a bit hard for me to track otherwise. Thanks!

**Comment by dvzrv** [comment]
@fancycode As this has been closed since July and there still has not been a release, can you please reopen this to track this issue?

Unfortunately, this software can not be packaged on a Linux distribution without a release being made.

**Comment by fancycode** [comment]
@dvzrv I have just released v0.1.0: https://github.com/strukturag/nextcloud-spreed-signaling/releases/tag/v0.1.0

**Comment by dvzrv** [comment]
@fancycode Cool stuff! Thanks a lot! :)

As soon as I have time for packaging I will get back to you and offer fixes in regards to that (if any).
