### ISSUE TITLE
"backend" parameter should be more flexible

### ISSUE THREAD

**Issue by joe-average-user** [strukturag/nextcloud-spreed-signaling#22]
while configuring the signaling server I had to find out that one has to name all hosts trying to use the server in the "backend=" config parameter. It would make life a lot easier if there were wildcards available or even better something like "[A.B.C.D]" - naming an IP to which the host should resolve.
The IP idea sounds not too complicated, what do you think?

**Comment by joe-average-user** [comment]
I would suggest to import "net" in backend_client.go, then modify:

func (b *BackendClient) IsUrlAllowed(u *url.URL) bool {
        if u == nil {
                // Reject all invalid URLs.
                return false
        }

        return b.whitelistAll || b.whitelist[u.Host]
}

to

func (b *BackendClient) IsUrlAllowed(u *url.URL) bool {
        if u == nil {
                // Reject all invalid URLs.
                return false
        }
        host,err := LookupHost(u.Host)
        return b.whitelistAll || b.whitelist[u.Host] || b.whitelist[host]
}

or equivalent working version ;-)
How about that?

**Comment by fancycode** [comment]
Work to support multiple Nextcloud Talk backends has started in #28 

I'm not sure why you would want to whitelist a single IP and allow all Nextcloud Talk instances running on that IP.

**Comment by joe-average-user** [comment]
You have no idea of webhosting? If you host quite a lot domains you really do not want to name every single one in the config. Given that some fluctuation takes place you have to edit the config every day. That is more than inconvenient. It is unusable. Instead you make a list of all hosting IPs (webservers) which indeed never change. And that's it.
We patched that in June with opening this issue and it works perfectly ever since.

**Comment by fancycode** [comment]
No need to be rude or making assumptions about me.

In your scenario, how do you make sure that users connected from different Nextcloud domains end up in different rooms on the signaling server if the Nextcloud room id is the same? E.g. Room `foobar123` on `cloud.domain1.tld` must be different on the signaling server than room `foobar123` on `cloud.domain2.tld`. This is not the case with your change, but will be possible with the changes in #28.

**Comment by joe-average-user** [comment]
Well, the domain isolation in Nextcloud is not working anyway. Users from cloud1.domain.tld see all kinds of users from cloud.domainX.tld in name completions, in search and about everywhere we tested that. Would be nice if it worked, though.
This is why we only use usernames like user1@domainX.tld (fully qualified with domain). At least there is a chance of recognising users of own domain then ...

**Comment by joe-average-user** [comment]
And I just checked your argument. I cannot find the rooms even in the same domain. At least search in Nextcloud Talk does not find them... Of course I can be invited by a moderator, though.

**Comment by fancycode** [comment]
> And I just checked your argument. I cannot find the rooms even in the same domain.

In the Nextcloud instances the rooms are separate, but in the signaling server all rooms `foobar123` from any NC instance would be the same room, so notifications from that room in `cloud.domain1.tld` would also be sent to connections in the same room on `cloud.domain2.tld`. The solution for that is #28.

**Comment by joe-average-user** [comment]
I just read some parts of #28 and would say it is absolutely unusable for a multi-domain hosting. If you have some thousand domains you end up in thousands of config lines and fluctuation will bring your setup to a halt, because you will have to reload everything when changing domains (which are separate backends on your #28 config). This is very bad and no solution to the problem. It would be a lot better to simply add the domain to room names somehow in the middle of the chain, best in nextcloud talk itself. So everything below will inherit this separation and nothing is to configure.

**Comment by joe-average-user** [comment]
Thinking some time about the issue it is obvious to me that the signal-server is the wrong place to solve the problem you address in #28. The servers' user (i.e. Nextcloud Talk) is responsible for creation of unique room names. But #28 tries to outsmart the user with own complex config options. This is the wrong way. If the user wants a rooms with name X, then the signal server should give it to him, no matter what the server thinks should be done. Sure you have a backend config, but this only regulates the basic access to the service. Of course you may do some kind of profiles for backends. But if you want 99% of the servers' users have the same profile you should not drive the setup into over-complexity. I wish you could think of a demo setup with 1000 domains where 10 are changing (i.e. added and removed) every day. Your goal must be to allow 100% production time throughout all days. A reload in your solution means downtime. In my patch you have no reload. If the resolved URL does not match the configured IP in the backend then it's out - no reload and no downtime needed for that.
Log example from running config:

Jul 22 11:35:27 mqtt-a01 signaling[295]: 2020/07/22 11:35:27.730578 backend_client.go:147: IsUrlAllowed? cloud.<domain>.<tld>
Jul 22 11:35:27 mqtt-a01 signaling[295]: 2020/07/22 11:35:27.733952 backend_client.go:157: IsUrlAllowed? looked up: cloud.<domain>.<tld> -> [A.B.C.D]

where A.B.C.D is a defined backend.

**Comment by fancycode** [comment]
The solution for that is to support hot-reload of the configuration without downtime or loading backend information from a database.

I will happily review pull-requests for such things but will stop with the discussion here.

**Comment by joe-average-user** [comment]
I think I understood you prefer large complex "solutions" which don't quite work in favor of small working ones.
You have no "hot-reload" up to now, have you? Thinking of it there is hardly one for any daemon I know managing a number of client connections (apache httpd can't either, but of course here are better programmers)...
I see it make sense to load one backend setup from a database - a one-record database?

**Comment by alexmo1997** [comment]
I don't think that a hot-reload would be that hard to implement. I suppose there just was no sufficient use-case for apache httpd to implement that. Furthermore do I not see how this is a "large complex "solution"". Adding a specific feature for the domains instead of a more widely usable for the configs (which would be relatively simple) wouldn't be a good solution imho.

**Comment by joe-average-user** [comment]
And that's the best part of my proposal: it is no "solution" in itself, it only enables you to define an IP as backend and not some URL. This allows every hoster to place an undefined number of domains/urls as clients for the signaling server without any further configuration. I have yet to see an argueable reason to deny this. It is not complicated in code, it is completely compatible in config. and it enables you to do a true multidomain setup which never needs to be touched again, no matter how many domains come and go. All you configure is:

[backend]
allowed = <cloudserver-IP>

And that's it.
Believe this: there is a lot people needing the httpd hot-reload, which is why a hack call "graceful" exists. It simply waits for the client connection to complete before stopping the corresponding thread. But that is not hot-reload. The truth is: hot-reload is a myth and hardly ever possible in real life. So your primary thought should always be to prevent such a need at all.
And in this case it is dead easy

**Comment by acsfer** [comment]
Sorry about my misunderstanding, but at this time, is it possible to set something like this to allow all sub-domains:

```
[backend]
allowed = *.example.com, example.net
```
?

**Comment by joe-average-user** [comment]
Indeed a complete misunderstanding: we are not talking about subdomains at all. We are talking about allowing domain1.net, domain2.com, domain3.org, domain4.de, domain5.fr, domain6.com.tw and so on. There is no name relation in the domains to allow. The only relation is the hosting IP. We are using the patch for almost a year now and did not have _any_ reload (hot or not), and no need to edit the config for a single case. We do believe though that there are non-technical reasons that this is not wanted.
