### ISSUE TITLE
Separate signaling messages for "session was removed" and "conversation was removed"

### ISSUE THREAD

**Issue by nickvergessen** [strukturag/nextcloud-spreed-signaling#25]
With https://github.com/nextcloud/spreed/pull/3591 we are improving the current world when people try to join twice in the same conversation. When your current session is removed a `disinvite` is sent and we show a message telling you:
> You joined the conversation in another window or device. This is currently not supported by Nextcloud Talk so this session was closed.

However we can not distinguish the disinvite from:
1. A moderator removed you from the conversation
2. You joined again and nextcloud send the HPB a "disinvite this session"
3. The conversation was removed completely.

Would it be possible to send different (or additional prior to the current one) messages so Talk can redirect you properly to a "The conversation does not exist" message?

**Comment by fancycode** [comment]
We can add an additional field to notify about the difference between `1` and `3`, how are you sending the `disinvite this session` in `2` and how is that forwarded to the user?

**Comment by nickvergessen** [comment]
`2` is the same as when a user leaves the room manually.
But when we can identify 1 and 3, we know 2 is the one without the extra reason. Totally fine :)
