### ISSUE TITLE
Deb/PPA packaging?

### ISSUE THREAD

**Issue by BloodyIron** [strukturag/nextcloud-spreed-signaling#27]
Any chance we can get this in a deb package and/or with a PPA repo? Great that this is open sourced, but compiling from source means package managers aren't kept in the loop, causing supportability challenges in production.

**Comment by morph027** [comment]
I've started some work here: https://gitlab.com/packaging/nextcloud-spreed-signaling/

**Comment by BloodyIron** [comment]
Yay!

**Comment by dvzrv** [comment]
To be able to package this software for any distribution in an official repository a release needs to be made.
Unfortunately the ticket for that (#21) has been closed without a release so far.

**Comment by fancycode** [comment]
We have releases since 0.1.0, closing then as packaging is not in the scope of this repository.

**Comment by BloodyIron** [comment]
So do we have a PPA/repo then? Because I don't see it mentioned or linked in this thread before being closed...

**Comment by fancycode** [comment]
https://github.com/strukturag/nextcloud-spreed-signaling/issues/27#issuecomment-679348032 above refers to a repository containing the packaging script and a readme on how to install the packages.
