### ISSUE TITLE
Error: Server responded with: 400

### ISSUE THREAD

**Issue by elhananjair** [strukturag/nextcloud-spreed-signaling#272]
Hello
I have finished configuring HPB and I just tried to check my configuration using `curl -i https://myserver.domain.invalid/standalone-signaling/api/v1/welcome` I am getting the following error in CLI and the Server responded with 400 on nextcloud talk setup. 

```
HTTP/2 400 
strict-transport-security: max-age=63072000
date: Thu, 09 Jun 2022 20:13:52 GMT
server: Apache/2.4.53 (Fedora Linux) OpenSSL/3.0.3
```

**Comment by elhananjair** [comment]
@fancycode any help, please...
I have checked the same issue raised on nextcloud forum (https://help.nextcloud.com/t/error-400-when-trying-to-access-high-performance-backend-signaling/106999/4) but that issue has been already fixed. Is there any way that I can fix this? 
Thank you.

**Comment by fancycode** [comment]
Did you check the actual URL that is called on the signaling server? You might have to enable additional logging in Apache.

**Comment by elhananjair** [comment]
Yes here is how I configured it:
![image](https://user-images.githubusercontent.com/69236638/173048079-7474964d-8945-4718-ab7d-137fa97db801.png)
Here is how I tried to connect from nextcloud to the signal server. 
![image](https://user-images.githubusercontent.com/69236638/173048384-8fc8d946-01fe-481c-bf3c-101caee9dea8.png)

**Comment by elhananjair** [comment]
I have set **ServerName** in the apache config with the same domain am using now to access the signaling server from nextcloud. 
```
<VirtualHost *:80>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/\.well\-known/acme\-challenge/
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt >> /path/to/signed_cert_and_intermediate_certs_and_dhparams
    SSLCertificateFile      /etc/letsencrypt/live/talk.acso.gov.et/fullchain.pem
    SSLCertificateKeyFile   /etc/letsencrypt/live/talk.acso.gov.et/privkey.pem
    ServerName talk.acso...

    # Enable proxying Websocket requests to the standalone signaling server.
    ProxyPass "/standalone-signaling/"  "ws://127.0.0.1:8443/"

    RewriteEngine On
    # Websocket connections from the clients.
    RewriteRule ^/standalone-signaling/spreed/$ - [L]
    # Backend connections from Nextcloud.
    RewriteRule ^/standalone-signaling/api/(.*) http://127.0.0.1:8443/api/$1 [L,P]
    # enable HTTP/2, if available
    Protocols h2 http/1.1

    # HTTP Strict Transport Security (mod_headers is required) (63072000 seconds)
    Header always set Strict-Transport-Security "max-age=63072000"
</VirtualHost>

```

**Comment by fancycode** [comment]
You are proxying to `localhost:8443`, is this the HTTP port of the signaling server?

Just to be sure, did you enable all necessary Apache modules?
```
a2enmod proxy
a2enmod proxy_http
a2enmod proxy_wstunnel
a2enmod rewrite
a2enmod ssl
```

**Comment by elhananjair** [comment]
@fancycode Thank you so much for helping me. 
I was using the HTTPS port but unfortunately in my apache config, I used HTTP in setting up a reverse proxy, my bad. 
I added this now to my apache config:
`SSLProxyEngine on`
and changed 
```
http://127.0.0.1:8443/api/$1 [L,P] to https://127.0.0.1:8443/api/$1 [L,P] and
"ws://127.0.0.1:8443/" to "wss://127.0.0.1:8443/"
```
and that 400 error is gone now but another issue came up, ` Error: Server responded with: 500`
The signal server shows this:` server.go:3197: http: TLS handshake error from 127.0.0.1:47254: EOF`
and apache error log shows this: 
`[proxy:error] [pid 17820:tid 17894] [client 192.168.195.130:48714] AH00898: Error during SSL Handshake with remote server returned /standalone-signaling/api/v1/welcome`

**Comment by fancycode** [comment]
There is no need to use HTTPS for the internal connection. Just use "ws://localhost:<port>" and "http://localhost:<port>" with the HTTP port of the signaling server.

**Comment by elhananjair** [comment]
Thank you so much now it is working. I miss understood this part from the doc I guess:
> Please note that you have to use https if your Nextcloud is also running on https. Usually, you should enter https://myhostname/standalone-signaling as URL.
![image](https://user-images.githubusercontent.com/69236638/173066333-fe343005-66de-4453-b1e9-760b0f2f8d09.png)

Now its shows ok, but unknown version, that won't cause problem right?

**Comment by elhananjair** [comment]
@fancycode I think everything is good now, hopefully, undetected running version unknown won't make serious issues. 
Thank you so much for such great work @fancycode.
