### ISSUE TITLE
Send "welcome" message immediately through websocket on connection

### ISSUE THREAD

**Issue by fancycode** [strukturag/nextcloud-spreed-signaling#273]
Should contain server version and feature flags, so clients can react to it and adjust their behaviour depending on feature flags (e.g. send hello v2).

Helps with #251

**Comment by fancycode** [comment]
@Ivansss @mahibi @timkrueger what happens in the current mobile Talk apps if the server sends a (to be defined) message with a new `type` initially before the client sends the `hello` request, will this be ignored?

The web client ignores such unknown messages:
https://github.com/nextcloud/spreed/blob/2048ef7528e71dd6dbb5473dd29ea461b72cb7d1/src/utils/signaling.js#L753

**Comment by Ivansss** [comment]
It will be ignored on iOS:
https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/NCExternalSignalingController.m#L430-L442

**Comment by timkrueger** [comment]
Sorry for the delay @fancycode 

It will also be ignored on Android:
https://github.com/nextcloud/talk-android/blob/db5ba9763f7dbcbb09702b6ee4b86b47efaa2561/app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java#L178-L344 (_Please take a few minutes and enjoy this wonderful switch-case statement._)

**Comment by fancycode** [comment]
Thanks @Ivansss and @timkrueger for the confirmations. So this is something I could go forward with.
