### ISSUE TITLE
json: cannot unmarshal array into Go struct field CapabilitiesResponse.capabilities of type map[string]interface {}

### ISSUE THREAD

**Issue by ftigges-comdev** [strukturag/nextcloud-spreed-signaling#284]
OS: Suse 15.3 
Go: v1.18

Hi,

after some networking hickups, I am getting some errors I can't solve.
Normally I wouldn't open a ticket. But there seems no other way to contact you..

Thanks for your efforts.
 

_**journalctl:**_

```
Jul 01 16:25:57 signaling signaling[2665]: client.go:282: Client from 46.114.153.126 has RTT of 64 ms (64.931951ms)
Jul 01 16:25:57 signaling signaling[2665]: capabilities.go:126: Capabilities expired for http://hostname.domain.tld/nextcloud/ocs/v2.php/cloud/capabilities, updating
Jul 01 16:25:57 signaling signaling[2665]: **capabilities.go:173: Could not decode OCS response body** {"version":{"major":24,"minor":0,"micro":1,"string":"24.0.1","edition":"","extendedSupport":false},"capabilities":{"bruteforce":{"delay":0},"metadataAvailable":[],"spreed":{"features":["audio","video","chat-v2","conversation-v4","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","delete-messages","mention-flag","in-call-flags","conversation-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms","listable-rooms","chat-read-marker","chat-unread","webinary-lobby","start-call-flag","chat-replies","circles-support","force-mute","sip-support","chat-read-status","phonebook-search","raise-hand","room-description","rich-object-sharing","temp-user-avatar-api","geo-location-sharing","voice-message-sharing","signaling-v3","publishing-permissions","clear-history","direct-mention-flag","notification-calls","conversation-permissions","rich-object-list-media","rich-object-delete","reactions","chat-reference-id"],"config":{"attachments":{"allowed":false},"chat":{"max-length":32000,"read-privacy":0},"conversations":{"can-create":false},"previews":{"max-gif-size":3145728}}},"theming":{"name":"company Cloud","url":"https:\/\/www.company.de","slogan":"ein sicherer Ort f\u00fcr company-Daten","color":"#294d7d","color-text":"#ffffff","color-element":"#294d7d","color-element-bright":"#294d7d","color-element-dark":"#294d7d","logo":"http:\/\/hostname.domain.tld\/nextcloud\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=12","background":"#294d7d","background-plain":true,"background-default":true,"logoheader":"http:\/\/hostname.domain.tld\/nextcloud\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=12","favicon":"http:\/\/hostname.domain.tld\/nextcloud\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=12"}}} from http://hostname.domain.tld/nextcloud/ocs/v2.php/cloud/capabilities: json: cannot unmarshal array into Go struct field CapabilitiesResponse.capabilities of type map[string]interface {}

...snip...

...snap...
Jul 01 16:30:25 signaling signaling[2665]: capabilities.go:191: Could not get capabilities forhttp://hostname.domain.tld/nextcloud/ocs/v2.php/apps/spreed/api/v3/signaling/backend: json: cannot unmarshal array into Go struct field CapabilitiesResponse.capabilities of type map[string]interface {}

```

When  calling from Clientside:

**_curl  -H "OCS-APIRequest: true" https://hostname.domain.tld/nextcloud/ocs/v2.php/apps/spreed/api/v3/signaling/backend_**
```

<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message/>
 </meta>
 <data>
  <element>
   <type>usersInRoom</type>
   <data/>
  </element>
 </data>
</ocs>

```

_**curl  -H "OCS-APIRequest: true" https://hostname.domain.tld/ocs/v2.php/cloud/capabilities**_
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message>OK</message>
 </meta>
 <data>
  <version>
   <major>24</major>
   <minor>0</minor>
   <micro>1</micro>
   <string>24.0.1</string>
   <edition></edition>
   <extendedSupport></extendedSupport>
  </version>
  <capabilities>
   <bruteforce>
    <delay>0</delay>
   </bruteforce>
   <metadataAvailable/>
   <spreed>
    <features>
     <element>audio</element>
     <element>video</element>
     <element>chat-v2</element>
     <element>conversation-v4</element>
     <element>guest-signaling</element>
     <element>empty-group-room</element>
     <element>guest-display-names</element>
     <element>multi-room-users</element>
     <element>favorites</element>
     <element>last-room-activity</element>
     <element>no-ping</element>
     <element>system-messages</element>
     <element>delete-messages</element>
     <element>mention-flag</element>
     <element>in-call-flags</element>
     <element>conversation-call-flags</element>
     <element>notification-levels</element>
     <element>invite-groups-and-mails</element>
     <element>locked-one-to-one-rooms</element>
     <element>read-only-rooms</element>
     <element>listable-rooms</element>
     <element>chat-read-marker</element>
     <element>chat-unread</element>
     <element>webinary-lobby</element>
     <element>start-call-flag</element>
     <element>chat-replies</element>
     <element>circles-support</element>
     <element>force-mute</element>
     <element>sip-support</element>
     <element>chat-read-status</element>
     <element>phonebook-search</element>
     <element>raise-hand</element>
     <element>room-description</element>
     <element>rich-object-sharing</element>
     <element>temp-user-avatar-api</element>
     <element>geo-location-sharing</element>
     <element>voice-message-sharing</element>
     <element>signaling-v3</element>
     <element>publishing-permissions</element>
     <element>clear-history</element>
     <element>direct-mention-flag</element>
     <element>notification-calls</element>
     <element>conversation-permissions</element>
     <element>rich-object-list-media</element>
     <element>rich-object-delete</element>
     <element>reactions</element>
     <element>chat-reference-id</element>
    </features>
    <config>
     <attachments>
      <allowed></allowed>
     </attachments>
     <chat>
      <max-length>32000</max-length>
      <read-privacy>0</read-privacy>
     </chat>
     <conversations>
      <can-create></can-create>
     </conversations>
     <previews>
      <max-gif-size>3145728</max-gif-size>
     </previews>
    </config>
   </spreed>
   <theming>
    <name>company Cloud</name>
    <url>https://www.company.de</url>
    <slogan>ein sicherer Ort für company-Daten</slogan>
    <color>#294d7d</color>
    <color-text>#ffffff</color-text>
    <color-element>#294d7d</color-element>
    <color-element-bright>#294d7d</color-element-bright>
    <color-element-dark>#294d7d</color-element-dark>
    <logo>https://hostname.domain.tld/index.php/apps/theming/image/logo?useSvg=1&amp;v=12</logo>
    <background>#294d7d</background>
    <background-plain>1</background-plain>
    <background-default>1</background-default>
    <logoheader>https://hostname.domain.tld/index.php/apps/theming/image/logo?useSvg=1&amp;v=12</logoheader>
    <favicon>https://hostname.domain.tld/index.php/apps/theming/image/logo?useSvg=1&amp;v=12</favicon>
   </theming>
  </capabilities>
 </data>
</ocs>
```

**Comment by fancycode** [comment]
The issue is triggered by the empty capabilities for `metadataAvailable` (the signaling server expects an object but got an array).

Could you please try https://github.com/strukturag/nextcloud-spreed-signaling/pull/287 and see if this fixes your issue? Thanks!

**Comment by fancycode** [comment]
> Normally I wouldn't open a ticket. But there seems no other way to contact you..

Opening a ticket is perfectly fine :smiley:

**Comment by ftigges-comdev** [comment]
I copied the three changed files from:

https://github.com/strukturag/nextcloud-spreed-signaling/archive/ec62503bd35a6691d7476810221cd71d589d97d1.zip

and restarted the service.
There seems to be no difference in behavior.

Gruß

Florian

capabilities.go:173: Could not decode OCS response body {"version":{"major":24,"minor":0,"micro":1,"string":"24.0.1","edition":"","extendedSupport":false},"capabilities":{"bruteforce":{"delay":0},"metadataAvailable":[],"spreed":{"features":["audio","video","chat-v2","conversation-v4","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","delete-messages","mention-flag","in-call-flags","conversation-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms","listable-rooms","chat-read-marker","chat-unread","webinary-lobby","start-call-flag","chat-replies","circles-support","force-mute","sip-support","chat-read-status","phonebook-search","raise-hand","room-description","rich-object-sharing","temp-user-avatar-api","geo-location-sharing","voice-message-sharing","signaling-v3","publishing-permissions","clear-history","direct-mention-flag","notification-calls","conversation-permissions","rich-object-list-media","rich-object-delete","reactions","chat-reference-id"],"config":{"attachments":{"allowed":false},"chat":{"max-length":32000,"read-privacy":0},"conversations":{"can-create":false},"previews":{"max-gif-size":3145728}}},"theming":{"name":"Company Cloud","url":"https:\/\/www.Company.de","slogan":"ein sicherer Ort f\u00fcr Company-Daten","color":"#294d7d","color-text":"#ffffff","color-element":"#294d7d","color-element-bright":"#294d7d","color-element-dark":"#294d7d","logo":"https:\/\/Hostname\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=12","background":"#294d7d","background-plain":true,"background-default":true,"logoheader":"https:\/\/Hostname\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=12","favicon":"https:\/\/Hostname\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=12"}}} from https://Hostname/ocs/v2.php/cloud/capabilities: json: cannot unmarshal array into Go struct field CapabilitiesResponse.capabilities of type map[string]interface {}

**Comment by fancycode** [comment]
Did you rebuild the service binary after copying the files? The field now has type `*json.RawMessage` instead of `map[string]interface{}`.

**Comment by ftigges-comdev** [comment]
Now I have... 
Seems to work..

Thanks a lot
Received capabilities map[config:map[attachments:map[allowed:false] chat:map[max-length:32000 read-privacy:0] conversations:map[can-create:false] previews:map[max-gif-size:3.145728e+06]] features:[audio video chat-v2 conversation-v4 guest-signaling empty-group-room guest-display-names multi-room-users favorites last-room-activity no-ping system-messages delete-messages mention-flag in-call-flags conversation-call-flags notification-levels invite-groups-and-mails locked-one-to-one-rooms read-only-rooms listable-rooms chat-read-marker chat-unread webinary-lobby start-call-flag chat-replies circles-support force-mute sip-support chat-read-status phonebook-search raise-hand room-description rich-object-sharing temp-user-avatar-api geo-location-sharing voice-message-sharing signaling-v3 publishing-permissions clear-history direct-mention-flag notification-calls conversation-permissions rich-object-list-media rich-object-delete reactions chat-reference-id]] from https:/
