### ISSUE TITLE
cannot see other users joining room on iOS

### ISSUE THREAD

**Issue by Chluz** [strukturag/nextcloud-spreed-signaling#309]
Hi, 

I set this up with Janus (latest commit from master). Testing from Android clients to other android clients of windows web browsers works fine. I essentially followed this guide, https://www.c-rieger.de/nextcloud-high-performance-backend-talk-app-und-signaling-server/ , and I had Stun and Turn working fine on another server with a dedicated public IP. 

However, using a iOS device with nextcloud talk i"m having issues:
- the iOS device is able to initiate the call
- The call will ring on the other participants devices
- The iOS device will show waiting for other participants to join room, indefinitely. 
- I see these types of errors in the log 
``` 
Jul 31 10:31:23 turn signaling[4640]: client.go:301: Error reading from client iEcPFr95coZjkW6plNxVuYAY35lUKZnHsc_z6KXmodified for posting STRNWGtuT3B2ek43bHwzMjI2NTI5NTYx: read tcp 127.0.0.1:8080->127.0.0.1:44648: i/o timeout
```

Any idea what might be going on ?
I'm guessing it has something to do with how iOS nextcloud talk app is managing calls - either triggering something wrong in my config, or showing a compatibility issue with the signaling server. 

Removing the signal server entries from my Nextcloud admin interface fixes everything. 

Thanks in advance !

**Comment by Ivansss** [comment]
Hi @Chluz :)
I guess you are using the latest Talk iOS version on the App Store, right?
At the moment, we are not aware of any issue when joining a call with the iOS app.
Is this issue reproducible every time you join a call using the iOS app in your setup?


@fancycode does this error ring any bells on your side?
```
Jul 31 10:31:23 turn signaling[4640]: client.go:301: Error reading from client iEcPFr95coZjkW6plNxVuYAY35lUKZnHsc_z6KXmodified for posting STRNWGtuT3B2ek43bHwzMjI2NTI5NTYx: read tcp 127.0.0.1:8080->127.0.0.1:44648: i/o timeout
```

**Comment by Chluz** [comment]
Hi @Ivansss Thanks for the reply, 

Its the latest version of Nextcloud Talk on iOS, namely 14.0.2 at the time of logging the issue. 
Server version of talk updated to the latest stable release, on the latest Nextcloud stable version. 

This issue is reproducible every time - I have not been able to get a single call through on iOS. 

My biggest issue is that I cannot understand the logs, or perhaps its that I don;t get logs on the iOS client side. I'm happy to investigate if you have an idea of where to start looking.

**Comment by fancycode** [comment]
> @fancycode does this error ring any bells on your side?
> 
> ```
> Jul 31 10:31:23 turn signaling[4640]: client.go:301: Error reading from client iEcPFr95coZjkW6plNxVuYAY35lUKZnHsc_z6KXmodified for posting STRNWGtuT3B2ek43bHwzMjI2NTI5NTYx: read tcp 127.0.0.1:8080->127.0.0.1:44648: i/o timeout
> ```

This is a rather generic error when the (proxied) connection between the webserver and the signaling server is closed / interrupted. Usually because the client connection to the webserver is closed / interrupted. Nothing that can be solved on the signaling server side.

**Comment by Ivansss** [comment]
Hello @Chluz 

So sorry for my very late reply. Are you still experiencing those issues with the Talk iOS app?
Could you try with the latest Talk iOS app release (v15.2.2)?
We have introduced some fixes for issues that could lead to the scenario you described ("waiting for other participants to join the call")
This issues were not easy to reproduce on our side but we experienced them from time to time.

**Comment by fancycode** [comment]
@Ivansss should we move this to the iOS app?

**Comment by Ivansss** [comment]
@fancycode fine by me ;)

**Comment by fancycode** [comment]
Just noticed you can only transfer issues between repositories of the same user / organization, so I can't move it to your Nextcloud repository :disappointed: 

@Chluz please reopen the issue in https://github.com/nextcloud/talk-ios if you can still reproduce the problem with the latest version of the iOS app. Thanks!
