### ISSUE TITLE
Build Docker image fails for version 1.0.0

### ISSUE THREAD

**Issue by Chartman123** [strukturag/nextcloud-spreed-signaling#311]
When trying to build the docker image it fails in step 5/12:

```
go: inconsistent vendoring in /workdir:
	google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor

make: *** [Makefile:67: /go/bin/protoc-gen-go-grpc] Error 1
```

**Comment by fancycode** [comment]
If you build with a `vendor` folder, you need to set `GOPROXY=off`.

**Comment by Chartman123** [comment]
Hi @fancycode,

thank you for the quick response :)

I'm using Portainer to build the image, there is no option to set anything there:

![grafik](https://user-images.githubusercontent.com/16020496/182856793-702a6fd1-17e0-4bcb-8369-554c648369b0.png)

Where do I have to set that?

**Comment by Chartman123** [comment]
Ok, using the source archive works just fine 🙂

**Comment by fancycode** [comment]
Sorry, I don't know about portainer but I could successfully build 1.0.0 from the (unmodified) release tarball with docker:
```
wget https://github.com/strukturag/nextcloud-spreed-signaling/releases/download/v1.0.0/nextcloud-spreed-signaling-v1.0.0.tar.gz
tar xf nextcloud-spreed-signaling-v1.0.0.tar.gz
cd nextcloud-spreed-signaling-v1.0.0/
docker build --rm -t test .
...
Step 5/12 : RUN make build
 ---> Running in 59a13a7e7b16
...
usr/local/go/bin/go build  -ldflags '-X main.version=unknown' -o "/workdir/bin"/signaling ./server/...
/usr/local/go/bin/go build  -ldflags '-X main.version=unknown' -o "/workdir/bin"/proxy ./proxy/...
go: downloading github.com/google/uuid v1.3.0
Removing intermediate container 59a13a7e7b16
...
 ---> 0dbe30bb2d05
Successfully built 0dbe30bb2d05
Successfully tagged test:latest
```

So my comment about `GOPROXY` was a bit quick and seems to be not necessary with plain Docker.

But glad you could resolve it by using the source archive ;-)
