### ISSUE TITLE
Ubuntu20.04 : failure after package update

### ISSUE THREAD

**Issue by francoisPE** [strukturag/nextcloud-spreed-signaling#315]
Hello,
I have a ubuntu VPS with a signaling server
My configuration was working properly up to yesterday when I upgrade package... (to version 1.0.2)
I see almost no message in syslog
```Aug  8 00:21:06 ns2 systemd[1]: signaling.service: Scheduled restart job, restart counter is at 170.
Aug  8 00:21:06 ns2 systemd[1]: Stopped Nextcloud Talk signaling server.
Aug  8 00:21:06 ns2 systemd[1]: Started Nextcloud Talk signaling server.
Aug  8 00:21:06 ns2 systemd[1]: signaling.service: Main process exited, code=killed, status=31/SYS
Aug  8 00:21:06 ns2 systemd[1]: signaling.service: Failed with result 'signal'.
Aug  8 00:21:06 ns2 kernel: [8136072.888627] audit: type=1326 audit(1659910866.720:18766): auid=4294967295 uid=126 gid=134 ses=4294967295 pid=2544650 comm="signaling" exe="/usr/bin/signaling" sig=31 arch=c000003e syscall=160 compat=0 ip=0x40444e code=0x80000000
Aug  8 00:21:08 ns2 systemd[1]: Stopped Nextcloud Talk signaling server.
```
service signaling status says
```● signaling.service - Nextcloud Talk signaling server
     Loaded: loaded (/lib/systemd/system/signaling.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: signal) since Mon 2022-08-08 00:31:49 CEST; 195ms ago
    Process: 2547319 ExecStart=/usr/bin/signaling --config /etc/signaling/server.conf (code=killed, signal=SYS)
   Main PID: 2547319 (code=killed, signal=SYS)

Aug 08 00:31:49 ns2.dgtz.fr systemd[1]: signaling.service: Main process exited, code=killed, status=31/SYS
Aug 08 00:31:49 ns2.dgtz.fr systemd[1]: signaling.service: Failed with result 'signal'.
```
That is very short...
Is there any incompatibility to check ?

**Comment by fancycode** [comment]
There is no version 1.0.2 of the signaling server yet, so I'm wondering what you are running. Was this prebuilt or did you compile it manually?

`SIGSYS` according to the manpage is `Bad system call (SVr4)`, so maybe you are enforcing some kind of security rules which block operations of the signaling server?

**Comment by francoisPE** [comment]
Sorry, for versioning : apt list says (I revert back my VPS yesterday night)
nextcloud-spreed-signaling/unknown 1.0.0-2 amd64 [upgradable from: 0.5.0-3]

It correspond to that page : https://github.com/strukturag/nextcloud-spreed-signaling/pkgs/container/nextcloud-spreed-signaling

Going from 0.5 to 1.0 needs to rework below 2 files ?
server.conf.in 
dist/init/systemd/signaling.service

**Comment by fancycode** [comment]
> It's in line with that page : https://github.com/strukturag/nextcloud-spreed-signaling/pkgs/container/nextcloud-spreed-signaling

This link points to Docker images but has nothing to do with any Ubuntu packages. You should check with the person providing your custom Ubuntu packages.

> Going from 0.5 to 1.0 needs to rework below 2 files ?

There have been a couple of configuration changes between 0.5 and 1.0, but in general it should be possible to run 1.0 with the config file from 0.5.

**Comment by francoisPE** [comment]
I'll try to find what's going on and let you know !
Thank you for your help

**Comment by fancycode** [comment]
Feel free to reopen if anything needs to be done here.

**Comment by morph027** [comment]
Packages should be from my repo. v1.0.0-3 has been fixed by removing `@resources` from `SystemCallFilter`, which has been introduced in https://github.com/strukturag/nextcloud-spreed-signaling/pull/276. Unfortunately somwhow missed this while testing the PR. Will create another PR to address this.
