### ISSUE TITLE
Unable to Join Call

### ISSUE THREAD

**Issue by zohaib09** [strukturag/nextcloud-spreed-signaling#319]
Hi

We have recently installed nextcloud-spreed-signaling by using this procedure: https://morph027.gitlab.io/blog/nextcloud-spreed-signaling/

while making call unable to receive calls by recipients, error received at signaling servers are:   client.go:303: Error reading from IP: read tcp 127.0.0.1:8080->127.0.0.1:57956: use of closed network >

Used apache as a reverse proxy. Signaling servers connects successfully in nextcloud talk settings.

Sometime participants join call but not audio received and then trying to connect: following error i can caught from logs

 janus[586273]: [ERR] [sdp-utils.c:janus_sdp_get_codec_rtpmap:763] Unsupported codec 'none'
 [ERR] [dtls.c:janus_dtls_srtp_incoming_msg:870] [5080426427583998]  -- 1 (srtp_err_status_fail)

Please help

**Comment by zohaib09** [comment]
Any suggestion please. require help

**Comment by zohaib09** [comment]
@morph027 please help, i have followed the procedure https://morph027.gitlab.io/blog/nextcloud-spreed-signaling/

having all above errors, please advice

**Comment by morph027** [comment]
Hm, not sure. Is nats-server running too? Which version of janus is installed?

I only did some packaging and do not have too much insights into the code itself....

**Comment by zohaib09** [comment]
@morph027 thank you for your reply. 

janus version

![image](https://user-images.githubusercontent.com/47688270/184162011-95d47ddc-866a-465c-8af1-dc85becf4db1.png)

service nats-server status

![image](https://user-images.githubusercontent.com/47688270/184162295-f65abaae-2fcd-4598-9b82-f10b864107e2.png)

![image](https://user-images.githubusercontent.com/47688270/184162450-82b5092d-88b6-4a79-b597-5347427f70da.png)

nats-server defined in server.conf

![image](https://user-images.githubusercontent.com/47688270/184162695-3f5fdb7e-3304-4047-94ba-999941aac875.png)


![image](https://user-images.githubusercontent.com/47688270/184162911-98c02e1d-bd87-49ef-8141-7ab555ee260f.png)


I don't know where is the mistake i followed same procedure.

**Comment by zohaib09** [comment]
i have upgraded janus still have same error

![image](https://user-images.githubusercontent.com/47688270/184194735-03401aa3-53db-4c50-91e6-7331d5bf43a4.png)

**Comment by muchahagrande** [comment]
Hi. I don't know if it's the same problem I'm experiencing, but recently I was unable to communicate with a partner through a public link. He is using Firefox, latest version.
Then I tested with Chromium and it worked, so I suspect that the problem started to happen at some of the latest Firefox upgrade or with the Spreed Signaling upgrade from 0.5.0 to 1.0.0 that I did some days ago.
I didn't have the time to do more testing yet.

**Comment by fancycode** [comment]
Did you configure a TURN server? This problem sounds more like a problem of the clients not being able to reach the Janus WebRTC gateway, than a problem with the signaling server.

**Comment by muchahagrande** [comment]
Hi, @fancycode 
I have TURN, NATS, Signaling and Janus configured. In fact, the configuration was working without problems till some days ago.
What I did is some testing, taking into account that the last two updates were Signaling and Firefox, I focused on these two components.
For example, I was able to connect using Chomium and Brave (both based on chrome), but not with Firefox. There are other browsers to test, but with those examples I suspect that Firefox update has something to do with the problem.

**Comment by muchahagrande** [comment]
Hi, yesterday I made a test with various versions of Firefox and found out that there's some change since version 98.0.1 that makes my configuration not to work properly.
Following @fancycode intuition I made many tests changing turn server configuration, and finally found that the exact same configuration doesn't work with docker version of Coturn but work's with the repo installation version.
The docker was running with Host networking, so there should be no difference, but who knows...
I don't know if this is the solution for the other users that faced the same problem...

**Comment by fancycode** [comment]
Thanks for your feedback, closing as this was an issue with the versions of Firefox / Coturn used.
