### ISSUE TITLE
Problems new official docker image

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [strukturag/nextcloud-spreed-signaling#323]
I use the new official docker repository of the spreed backend.
I have setup the following variables from the previous setup with docker-compose.yml (is still working if I just download the repo and use the docker-compose.yml).
The private stuff is blacked out.
Nevertheless, I don’t see all env variables when i do printenv in the container.

The connection does not work as it was working before (docker-compose.yml) from outside of the container.
The image should run janus, turn and stun.
Settings at the screenshot.

![image](https://user-images.githubusercontent.com/17781278/185858958-ebfc557a-a70b-4916-92c1-9f5dcb0064e3.png)

**Comment by fancycode** [comment]
The official images only provide the signaling server / -proxy. If you also need Janus / Coturn / NATS, you will still need docker-compose or similar to run the other services.
