### ISSUE TITLE
[Help Request]-Spreed Standalone Signaling server

### ISSUE THREAD

**Issue by Still-not-found** [strukturag/nextcloud-spreed-signaling#325]
Using this Spreed-Standalone Signaling server, maximum of  how many participants  can i host ? and also I would like to know that by Installing and configuring multiple signaling servers , is that possible to host more than 500+ active participants simultaneously in a single video conference.

**Comment by fancycode** [comment]
The scaling doesn't really depend on the signaling server, but the Janus WebRTC service. For this number of participants, you most likely will need multiple WebRTC servers.
