### ISSUE TITLE
Turnserver connection issue

### ISSUE THREAD

**Issue by francoisPE** [strukturag/nextcloud-spreed-signaling#329]
Hello, 
I have a signaling server set up on a VPS that is working quite well except sometimes, when for any reason it is failing.
There are different visible issues: in most cases, mic is suddenly cut off. But previously, it was a fully lost connection.
I dig that so many times.

When looking at logs I always see, that sequences of errors:
```
Aug  2 09:59:14 ns2 janus[210885]: [972604436030583] Creating ICE agent (ICE Full mode, controlled)
Aug  2 09:59:14 ns2 janus[210885]: nice_agent_set_relay_info: assertion 'username' failed
Aug  2 09:59:14 ns2 janus[210885]: [WARN] Could not set TURN server, is the address correct? (127.0.0.1:5349)
Aug  2 09:59:14 ns2 janus[210885]: [WARN] [972604436030583]     Missing valid SRTP session (packet arrived too early?), skipping...
```

Obviously, there is a turnserver at 127.0.0.1:5349 because it is working most of the time !
But why it is trying to connect with username for nice_agent_set_relay_info

in janus.jcfg, I have
```
nat: {
                stun_server = "127.0.0.1"
                stun_port = 5349
                full_trickle = true
                turn_server = "127.0.0.1"
                turn_port = 5349
                turn_type = "udp"
                #turn_rest_api = "commented -> not set"
                turn_rest_api_key = "613xxhiddenxx3A"
}
```
Is anyone having an idea ?
Many thanks

My conf
coturn/focal-updates,focal-security,now 4.5.1.1-1.1ubuntu0.20.04.2 amd64 [installed]
janus/unknown,now 0.11.2-1 amd64 [installed]
nats-server/unknown,now 2.8.4-11 amd64 [installed]
nextcloud-spreed-signaling-proxy/unknown 1.0.0-3 amd64
nextcloud-spreed-signaling/unknown 1.0.0-3 amd64 [upgradable from: 0.5.0-3]
(I will upgrade, but, I would like to solve above issue first)

**Comment by fancycode** [comment]
As you have a `turn_server` configured, Janus will enable TURN:
https://github.com/meetecho/janus-gateway/blob/84296302d931e5d86e2f131977fbdc8a4d8de737/ice.c#L3846

No `turn_user` / `turn_pwd` are configured, so the username / password for TURN will be empty. Are you sure you need TURN in Janus?
https://github.com/meetecho/janus-gateway/blob/84296302d931e5d86e2f131977fbdc8a4d8de737/conf/janus.jcfg.sample.in#L319

Anway, this is not an issue of the signaling server, but of your setup / configuration.

**Comment by francoisPE** [comment]
Hello,
To set up, I follow: https://markus-blog.de/index.php/2020/07/30/how-to-install-nextcloud-talk-high-performance-backend-with-stun-turnserver-on-ubuntu/
In this, it defines a dynamic credential with turn_rest_api_key 

When reviewing https://github.com/meetecho/janus-gateway/blob/84296302d931e5d86e2f131977fbdc8a4d8de737/ice.c#L3846
```
	/* Any dynamic TURN credentials to retrieve via REST API? */
	gboolean have_turnrest_credentials = FALSE;
#ifdef HAVE_TURNRESTAPI
	/* When using the TURN REST API, we use the handle's opaque_id as a username
	 * by default, and fall back to the session_id when it's missing. Refer to this
	 * issue for more context: https://github.com/meetecho/janus-gateway/issues/2199 */
	char turnrest_username[20];
	if(handle->opaque_id == NULL) {
		janus_session *session = (janus_session *)handle->session;
		g_snprintf(turnrest_username, sizeof(turnrest_username), "%"SCNu64, session->session_id);
	}
	janus_turnrest_response *turnrest_credentials = janus_turnrest_request((const char *)(handle->opaque_id ?
		handle->opaque_id : turnrest_username));
	if(turnrest_credentials != NULL) {
		have_turnrest_credentials = TRUE;
		JANUS_LOG(LOG_VERB, "[%"SCNu64"] Got credentials from the TURN REST API backend!\n", handle->handle_id);
		JANUS_LOG(LOG_HUGE, "  -- Username: %s\n", turnrest_credentials->username);
		JANUS_LOG(LOG_HUGE, "  -- Password: %s\n", turnrest_credentials->password);
		JANUS_LOG(LOG_HUGE, "  -- TTL:      %"SCNu32"\n", turnrest_credentials->ttl);
		JANUS_LOG(LOG_HUGE, "  -- Servers:  %d\n", g_list_length(turnrest_credentials->servers));
		GList *server = turnrest_credentials->servers;
		while(server != NULL) {
			janus_turnrest_instance *instance = (janus_turnrest_instance *)server->data;
			JANUS_LOG(LOG_HUGE, "  -- -- URI: %s:%"SCNu16" (%d)\n", instance->server, instance->port, instance->transport);
			server = server->next;
		}
	}
```
It seems dynamic credential is not allowed as it is looking for username and password.
So i'll try without turnserver.
Let see

**Comment by fancycode** [comment]
For the dynamic allocation of username / password you need to setup a server in `turn_rest_api` (which is commented out in your example above):
https://github.com/meetecho/janus-gateway/blob/84296302d931e5d86e2f131977fbdc8a4d8de737/conf/janus.jcfg.sample.in#L334

**Comment by francoisPE** [comment]
Thanks to your very big help, I made 2 tests.
1. No turn for janus 
2. Turn Api for janus
As you mention, turn for janus is needed if behind a firewall : this is not my case.

Test 1. gives no ERR except handshake is very long. But could be something else ! (warn msg : Missing valid SRTP session (packet arrived too early?), skipping...)

Test 2.  gives '[ERR] [turnrest.c:janus_turnrest_request:180] Couldn't send the request: Failure when receiving data from the peer'

Thus, I go without turnserver for janus.
Let see how it works...

Thanks a lot to you :-)

**Comment by francoisPE** [comment]
Hello,
I am back on that topic.
My issue is that micro is not working.
I no more have above error in log.

What janus is saying is :
```
Sep 30 10:26:00 xx janus[546812]: [3773999828747737]  Got an RTCP packet
Sep 30 10:26:00 xx janus[546812]: [6617414772984618] RFC4588 rtx packet on video (SSRC 917730822)...
Sep 30 10:26:00 xx janus[546812]: [3773999828747737] Incoming RTCP, bundling: this is video **(no audio has been negotiated)**
Sep 30 10:26:00 xx janus[546812]: [3773999828747737] Incoming RTCP, bundling: this is video (local SSRC: video=2621543843, got 2621543843)
Sep 30 10:26:00 xx janus[546812]:    Parsing compound packet (total of 32 bytes)
Sep 30 10:26:00 xx janus[546812]:      #1 RR (201)
Sep 30 10:26:00 xx janus[546812]: jitter=539.000000, fraction=0, loss=0
Sep 30 10:26:00 xx janus[546812]: rtt=21
Sep 30 10:26:00 xx janus[546812]:        RTCP PT 201, length: 32 bytes
Sep 30 10:26:00 xx janus[546812]: [3773999828747737] Got video RTCP (32 bytes)
```
For me, the problem is that there is no micro, because only video is negociated.
I try to see what signaling is requesting, but, I don't see how to increase signaling loglevel.

**Comment by fancycode** [comment]
What is negotiated totally depends on the clients. The signaling server is just passing along the requests. So if a client doesn't negotiate audio, there is nothing the signaling server can do about it.

**Comment by francoisPE** [comment]
Thanks a lot for your reply.
I found finally, this is 'sessionlimit' parameter that is bringing that problems.

I wonder if a verbose mode exist for signaling... It would help quite a bit :-)
