### ISSUE TITLE
Allow use of shared secret for individual backends

### ISSUE THREAD

**Issue by solracsf** [strukturag/nextcloud-spreed-signaling#337]
When https://github.com/strukturag/nextcloud-spreed-signaling/blob/master/server.conf.in#L89-L92 is set, if individual backends secret is not set, this could be used. As per code comment, it is used only if `allowall` is enabled.

It would allow to set the same `secret=` for all backends, differentiated only by `url=`
Logic would become: 
```
if [individual backend has secret set]
  use it
else
  use shared secret
```

**Comment by fancycode** [comment]
Good idea, I don't have an ETA when I could work on this though.
