### ISSUE TITLE
Nextcloud 25.0.0 talk compability issue

### ISSUE THREAD

**Issue by deeztek** [strukturag/nextcloud-spreed-signaling#356]
Hello,

Getting the following error trying to connect using Nextcloud version 25.0.0

![image](https://user-images.githubusercontent.com/17934095/199027172-71fd7dc8-4e37-4863-b202-3175c6fee9f6.png)

Nextcloud 24.0.3 does not seem to have this issue.

**Comment by MrHoschie** [comment]
Hi,
I can confirm this. 
In addition: after updating the singaling I get the same behaviour as #342 
By deleting the address of the HPB everything worked as expected, re-add the HPB connection will remain in #342

**Comment by fancycode** [comment]
The commit in your screenshot (e4214eb) hints at a version around 0.4.1. As Nextcloud Talk 25 requires the feature flag `incall-all` from #208, you will need to upgrade the signaling server to at least version 0.5.0 (or better directly to the latest version).

Talk checks if the signaling server supports all necessary features and will show the message if not.

**Comment by deeztek** [comment]
Sorry but I'm a little confused here. How exactly am I supposed to get the latest version? I would think git cloning the repo would give me the latest code.

I use docker compose so I clone the repo and build the image from it. That's what I did before posting and that's how I got https://github.com/strukturag/nextcloud-spreed-signaling/commit/e4214eb95dee09d564c71227eb554f3084a726d4

**Comment by Mer0me** [comment]
I have the same problem : upgrading to Nextcloud 25 apparently breaks the compatibilty Talk <-> signaling server.
I have no idea how I should update the dockered signaling server (is there a howto somewhere ?). Fortunately, Talk seems to work as expected even if the message "Server needs to be updated" is showed.
Maybe it lacks some new features, but how to know that ?

**Comment by deeztek** [comment]
So issues get closed with no resolution?

**Comment by Fuseteam** [comment]
when did you clone the git repo? it appears that 0.5 was released 2nd June

**Comment by fancycode** [comment]
> So issues get closed with no resolution?

The resolution is to rebuild the signaling server from a newer version as written above. How to do this depends on your installation and how you did that for the older version. In general, cloning a later commit and rebuilding from there will work.

If you are using Docker, you could also use the official image from https://hub.docker.com/r/strukturag/nextcloud-spreed-signaling
