### ISSUE TITLE
Video and audio not working in video chat with signaling server

### ISSUE THREAD

**Issue by digitalrevisor** [strukturag/nextcloud-spreed-signaling#38]
Hi.

I've tried setting up the Signaling Server & Janus according to the instructions here, but I've gotten to an issue I'm not sure how to solve.

So the Signaling Server, Janus, nats etc seems to be up and running. In Nextcloud Talk settings, we get an "OK" from the TURN server and Signaling Server. I've entered them like this:
TURN Server: our.domain.com:3478
Signaling Server: https://our.domain.com/standalone-signaling

However, when entering a video chat in TALK, it doesn't work.

Step by Step:
1. User A creates group conversation.
2. User A invites User B into the group.
3. User A starts a call. He can see his own video (webcam).
4. User B joins the call. He can see his own video (webcam).
5. Both users are unable to see eachothers video or hear audio from eachother.

I've gone through our configurations multiple times now but I can't see what is wrong. I tried to remove and then make the Signaling Server again, but it didn't change anything.

In the Signaling Server console nothing unatural appear until the second person (e.g User B) joins the conversation. Then we get some error from Janus.

`2020/08/12 08:11:34.980192 mcu_janus.go:673: Publisher 4138884646681718 received connected
2020/08/12 08:11:35.424210 mcu_janus.go:506: Started listener &{{janus.plugin.videoroom map[room:1820587936572240 started:ok videoroom:event]} map[] 5800955549083094 2175678738512156}
2020/08/12 08:11:35.578720 mcu_janus.go:954: Subscriber 2175678738512156 received hangup (DTLS alert), closing
2020/08/12 08:11:35.579253 janus_client.go:473: Unable to deliver message {
   "janus": "detached",
   "session_id": 5800955549083094,
   "sender": 2175678738512156
}. Handle 2175678738512156 gone?
2020/08/12 08:11:35.610435 hub.go:1329: No MCU subscriber found for session gkmV8MgM_lujxyjgwVt6WjEFIe6sk-GbFd4E8sPEjg98PT1nd1FVcDR3S0ZoeFZQQmt3SmpEUHFRMU11VHFUZHR4NUlLU0xFWFpNck9ydlJQd21zS3BoMGJBdE1jZHpJTWVmMy1BcnRKaTdVVmQ3TWI5SE1PVWdCRTMwMnlTVEp5alBGVWZyVExrdGlnR3hoM2tLcHV4d01scm9oTHg5dk5xcHFkczI3T2NWSEFVc0xUOUZZOXhvRGhIdGpmZzBhZnExWDZacTlzOTFvU3w3Nzg5MTI3OTUx to send &{Type:candidate Sid:1597219893463 RoomType:video Payload:map[candidate:map[candidate:candidate:2644336306 1 udp 2122260223 192.168.2.117 58769 typ host generation 0 ufrag +zuR network-id 1 network-cost 10 sdpMLineIndex:0 sdpMid:audio]]} to mvlCnxjfdc6qCWVt3nV1-zUO5nxvpBYfIlBMHOatbSZ8PT1BTzZzdnNhRmVSbXZYdGx5b3VOMWxjRWEtbDdBbTBxWGQ0SFpFdjZmaW94YVB1NXltYl81dzR3U0l1dFJJWXJxVWdjVGZaVWRodk9YYzg4SHpKYmNWSWZTTjcxTnVTV243VU1IdDFRQnRUYmNReWZoakZBWm14blROUmxpakhMbVZNUEFwZnJSX2ppN1I4dVJMQlVETm5JQkdpUEY3b2VkWEJQZUg4LTQ4OXw0ODg5MTI3OTUx`

This error keeps repeating until the call ends.

Any clue what the issue could be here?

**Comment by fancycode** [comment]
Are firewall ports open so Janus can be reached? Did you check the logs of the Janus server?

Also you can check the browser for any WebRTC related output (e.g. "chrome://webrtc-internals" in Chrome).

**Comment by digitalrevisor** [comment]
Hi. Firewall ports are open (and I even tried with firewall disabled).

But I did check the Janus and noticed that it was far too large. I moved it away and suddendly things started working much better. With PC/Mac only we were able to have 1v1 video chats and group chats with 3 people with little issue. I don't excatly know what caused this issue, but I've set up log rotation now so hopefully the log file won't get too big again.

However, there are still issues with mobile devices. They keep having problem connecting. Either not showing up at all, or missing either audio or video, even though it says in the text chat that they've joined. We've tried android and iphone and both seem to have the same issue. Any ideas?

**Comment by fancycode** [comment]
So Janus is working with the browser? Then this could be an issue of the Talk mobile apps, @Ivansss any ideas for iOS?

**Comment by digitalrevisor** [comment]
Yeah as far as I can tell it works with the browser fine. Conversations with a few people on PC/mac was OK, issues began when we tried to join with mobile devices. Tried with samsung and iphone and huawei.

**Comment by digitalrevisor** [comment]
Any further development on this issue here? If this isn't something wrong with the talk apps but with the talk mobile apps instead, is there another repository I should post about this in? We haven't been able to figure out anything from our side that could be causing the issue for mobile applications.

**Comment by fancycode** [comment]
Best would probably to open issues in the repositories of the mobile apps. If everything is working in the browser, I don't see where the signaling server could cause issues.

Here are the links:
- Android app: https://github.com/nextcloud/talk-android
- iOS app: https://github.com/nextcloud/talk-ios
