### ISSUE TITLE
Communication between signaling and Janus

### ISSUE THREAD

**Issue by elhananjair** [strukturag/nextcloud-spreed-signaling#392]
Hello there lately I have update Janus and video calls are not working for me, I checked janus service and got the following error:

> [ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:9679] No such feed (1)

and here is the output of NATS service
> [::1]:43118 - cid:32901 - Client parser ERROR, state=0, i=0: proto='"GET /varz HTTP/1.1\r\nHost: localh"...'

There might be a problem I guess when updating is done with sub-systems of spreed-signaling such as Janus and NATS.

**Comment by fancycode** [comment]
I'm afraid I will need more information what you tried to do and what the problem is. Can clients connect to the signaling server and is the Janus gateway reachable by all clients? You might need a TURN server if some clients are behind a firewall and communication with the Janus gateway might not be possible.

> [ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:9679] No such feed (1)

This could happen if a participant tries to subscribe a stream that is not published yet. Could you please check for logs of the signaling server at the same time?

**Comment by elhananjair** [comment]
Hello @fancycode 
> Can clients connect to the signaling server and is the Janus gateway reachable by all clients? You might need a TURN server if some clients are behind a firewall and communication with the Janus gateway might not be possible.

you were right the problem was janus not accessible for clients behind a firewall, I added TURN server values in janus configs and it works now. Thank you

**Comment by ETLin** [comment]
hi i got the same issue. how did you fix it?
Creating new handle in session 8151947473756861: 4659428534753887; 0x7fd6a8aedce0 0x7fd6a73ece00
[497517584970634] Creating ICE agent (ICE Full mode, controlled)
[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:6585] No such feed (1)
[WARN] [85634196554843] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
[WARN] [85634196554843] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
[WARN] [85634196554843] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
[WARN] [85634196554843] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
Detaching handle from JANUS VideoRoom plugin; 0x7fd6a73ece00 0x7fd6a740caf0 0x7fd6a73ece00 0x7fd6a7507880
[janus.plugin.videoroom-0x7fd6a740caf0] No WebRTC media anymore; 0x7fd6a73ece00 0x7fd6a7507880

tuned some params in janus.jcfg? like setting of turn server?

**Comment by elhananjair** [comment]
> tuned some params in janus.jcfg? like setting of turn server?
Yeah I just added IP and Password for turn server in janus.jcfg and it worked.

**Comment by fancycode** [comment]
> [WARN] [85634196554843] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)

This is about the connection between a client and Janus, not between the signaling server and Janus. Adding a TURN server should help resolve this.
