### ISSUE TITLE
Add specific message for switching to other room

### ISSUE THREAD

**Issue by danxuliu** [strukturag/nextcloud-spreed-signaling#398]
In Talk we need to [send a signaling message from the server to the participants in a conversation to instruct their clients to switch to a different conversation](https://github.com/nextcloud/spreed/pull/8477). Currently this is done with a generic message that includes information about the target rooms (currently only the token, but it could be extended in the future, for example, with the permissions) indexed by the session IDs of the participants.

There are a couple of issues with that approach:
- The session ID received by the clients is the Nextcloud session ID; all the signaling messages sent from the server initially provide the Nextcloud session ID, but if the signaling server has a specific handler for the message the Nextcloud session ID is translated to the signaling session ID, and that is the session ID received by the clients. However, if the signaling message is a generic one it is just relayed as is to the clients, so in this case they receive the Nextcloud session ID instead.
- All the clients receive a signaling message for any participant in the room that has to switch to another room.

Due to this it would be good to add a specific signaling message to notify a client that it needs to switch to another room.

This is the proposed message format that would be sent from Nextcloud server to the signaling server:
```
{
  "type": "switchto",
  "switchto": [
    "SESSION_ID_1": {
      "roomid": "TARGET_ROOM_TOKEN",
      (maybe other properties in the future),
    },
    "SESSION_ID_2": {
      "roomid": "TARGET_ROOM_TOKEN",
      (maybe other properties in the future),
    },
    ...
  ],
}
```

This is the proposed message format that would be sent from the signaling server to the clients (with only the data for that client):
```
{
  "type": "event",
  "event": {
    "target": "participants",
    "type": "switchto",
    "switchto": {
      "roomid": "TARGET_ROOM_TOKEN",
      (maybe other properties in the future),
    },
  },
}
```

Both message formats are just proposals, but of course they can be adjusted as needed :-)

**Comment by fancycode** [comment]
> This is the proposed message format that would be sent from Nextcloud server to the signaling server:

With this you are duplicating the target room token a lot, what do you think about something like this:
```json
{
  "type": "switchto",
  "switchto": [
    "room": "TARGET_ROOM_TOKEN",
    "properties": {
      ...properties of the target room for the room event below...
    },
    "sessions": {
      "SESSION_ID_1": {
        (maybe other properties in the future),
      },
      "SESSION_ID_2": {
        (maybe other properties in the future),
      }
    },
    ...
  ],
}
```

> This is the proposed message format that would be sent from the signaling server to the clients (with only the data for that client):

Here we could use existing `room` event (see https://nextcloud-spreed-signaling.readthedocs.io/en/latest/standalone-signaling-api-v1/#join-room, under `Message format (Server -> Client)`). At least the idea was that this could be sent by the server to tell the client to switch the room. You could use the room properties to flag the new room as a breakout room.

**Comment by fancycode** [comment]
> > With this you are duplicating the target room token a lot, what do you think about something like this:
> 
> Totally fine. As different participants will need to switch to different rooms the new format will require several messages, but I guess that should not be a problem and, in fact, it can help to avoid hitting the message length limit.

Ok, so we will go with the format I suggested?

> > Here we could use existing `room` event (see https://nextcloud-spreed-signaling.readthedocs.io/en/latest/standalone-signaling-api-v1/#join-room, under `Message format (Server -> Client)`). At least the idea was that this could be sent by the server to tell the client to switch the room. You could use the room properties to flag the new room as a breakout room.
> 
> I was not aware that the `room` event could be already sent without a request from the client to join a room. If I am not mistaken none of the Talk clients handle that... see_no_evil However, if I understand it right, if that message is sent that means that the client was moved already? That is, that its participant left the previous room and joined the new one in the Nextcloud server itself, without client interaction. How would that work regarding the PHP session? If I am not mistaken although the signaling session ID is still the same when a participant leaves a room and joins another one a different PHP session is given.

I don't think it's used right now but the idea was that it *could* be used to move clients from the serverside. However as you pointed out, there might be a problem with the PHP session if this still has the client in the old room.

> In any case, my current idea would be that the clients explicitly leave the previous room and join the new one when they receive the message to switch to another room (even if that means that a bad behaved client could ignore it and stay in the previous room, although for the current use case that should not be problematic), but that nothing special is done server side. Would the `room` event be suitable for that?

Totally fine by me and from an API standpoint it's probably cleaner anyway to have a dedicated message to move clients between rooms. We can still add code to the server to check if a client really did follow the message and switched to the new room and if not, disconnect it with an error message (just like the server does if no room is joined initially).
