### ISSUE TITLE
continentmap.go make not found Ubuntu 20.04

### ISSUE THREAD

**Issue by Dark-Schnitzel** [strukturag/nextcloud-spreed-signaling#4]
OS: Ubuntu 20.04
go: 1.13.8

Hello, i tried to build the server but unfortunately continentmap.go cant be found. i also havent found this file under /src/signaling

root@ubuntu-1:/home/hank/nextcloud-spreed-signaling-master# make build [ ! -d "/home/hank/nextcloud-spreed-signaling-master/.git/hooks" ] || ln -sf "/home/hank/nextcloud-spreed-signaling-master/scripts/pre-commit.hook" "/home/hank/nextcloud-spreed-signaling-master/.git/hooks/pre-commit" GOPATH="/home/hank/nextcloud-spreed-signaling-master/vendor:/home/hank/nextcloud-spreed-signaling-master" /usr/bin/go get github.com/rogpeppe/godeps /home/hank/nextcloud-spreed-signaling-master/scripts/get_continent_map.py src/signaling/continentmap.go make: /home/hank/nextcloud-spreed-signaling-master/scripts/get_continent_map.py: Command not found make: *** [Makefile:56: src/signaling/continentmap.go] Error 127

**Comment by morph027** [comment]
Probably due to the error: `Command not found make`

If you'r running docker (anyone should ;)), try this:

```bash
docker run --rm -it --name golang golang:latest
go get github.com/strukturag/nextcloud-spreed-signaling
cd src/github.com/strukturag/nextcloud-spreed-signaling/
make build
# leave terminal open
# in another terminal window
docker cp golang:/go/src/github.com/strukturag/nextcloud-spreed-signaling/bin/signaling .
# now exit your docker container
```

**Comment by morph027** [comment]
I've setup a package repo for ubuntu which includes the latest build: https://gitlab.com/packaging/nextcloud-spreed-signaling

**Comment by Dark-Schnitzel** [comment]
Okay, its an ubuntu installation without docker.
i tried "go get github.com/strukturag/nextcloud-spreed-signaling" and got this:
`root@ubuntu-1:/home/hank# go get github.com/strukturag/nextcloud-spreed-signaling
package github.com/strukturag/nextcloud-spreed-signaling: no Go files in /root/go/src/github.com/strukturag/nextcloud-spreed-signaling`

afterwards in that directory i get the same build error

**Comment by Dark-Schnitzel** [comment]
The Package seems to work, good job, service is up and running.
Steps after Installation needed: 
create /etc/signaling
copy server.config.in to /etc/signaling

**Comment by fancycode** [comment]
The `continentmap.go` file is generated by the script in https://github.com/strukturag/nextcloud-spreed-signaling/blob/master/scripts/get_continent_map.py

It uses Python to run, so most likely you don't have that installed and therefore get the `Command not found` error.
