### ISSUE TITLE
Don't send "ping" requests for internal sessions

### ISSUE THREAD

**Issue by fancycode** [strukturag/nextcloud-spreed-signaling#419]
Internal sessions should not be included in the "ping" requests that are sent to Nextcloud periodically. They will be ignored anyway as there is no associated session for them.

**Comment by fancycode** [comment]
This should already be the case. When determining the sessions to send a "ping" for, only sessions with a `RoomSessionId` (which is the Nextcloud Talk session id) are used:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/d56e67387b485f252812d23001b435eb559d8e5a/room.go#L888

Internal sessions don't have such a Talk session id and thus should get skipped.

@danxuliu as you reported this, how do your internal sessions join a room?

**Comment by danxuliu** [comment]
> @danxuliu as you reported this, how do your internal sessions join a room?

Like regular sessions, [using a `room` message](https://github.com/nextcloud/spreed/blob/4511978305c16028b5e3e23b91708693068a0458/src/utils/signaling.js#L1113-L1122) (which is probably wrong... :-) ).

You can reproduce the behaviour with https://github.com/nextcloud/spreed/pull/8756 (without having to do an actual recording):
- In the browser open the URL of a call followed by `/recording` (_https://cloud.yourdomain.com/index.php/call/CONVERSATION_TOKEN/recording_)
- In the browser console, execute `OCA.Talk.signalingJoinCallForRecording('CONVERSATION_TOKEN', await OCA.Talk.getSignalingSettings(), { random: 'SOME_RANDOM_VALUE', token: 'RANDOM_HASHED_WITH_THE_INTERNAL_SECRET', backend: 'https://invalid.backend' })`
- After a few seconds the error about pings is shown in the signaling logs

Nevertheless, if a proper backend is used everything seems to work as expected.

**Comment by fancycode** [comment]
With this code, you are including a Nextcloud session id (which is the `RoomSessionId` in the signaling server) in the request to join the room. The ping code will send pings for all sessions with such an id, so this works as intended. I would rather not always skip the internal sessions here, as we might want to have internal sessions with an associated session in Nextcloud in the future.

For internal sessions you can omit the Nextcloud session id and they won't be included in the ping messages. Internal sessions can join any room and no request will performed to Nextcloud for checking if it's allowed.

**Comment by danxuliu** [comment]
> With this code, you are including a Nextcloud session id (which is the `RoomSessionId` in the signaling server) in the request to join the room. The ping code will send pings for all sessions with such an id, so this works as intended. I would rather not always skip the internal sessions here, as we might want to have internal sessions with an associated session in Nextcloud in the future.

:+1: 

> For internal sessions you can omit the Nextcloud session id and they won't be included in the ping messages. Internal sessions can join any room and no request will performed to Nextcloud for checking if it's allowed.

See? I knew it was wrong :-P I will adjust it. Thanks and sorry for the noise!

**Comment by fancycode** [comment]
No problem :-)
