### ISSUE TITLE
Docker 1.1 doesn't start

### ISSUE THREAD

**Issue by Chartman123** [strukturag/nextcloud-spreed-signaling#424]
The docker container version 1.1 from hub.docker.com shows an error when it's starting:

`Error loading shared library libresolv.so.2: No such file or directory (needed by /usr/bin/nextcloud-spreed-signaling)`

**Comment by fancycode** [comment]
Thanks for the heads up, will be fixed with #425 and I'll release 1.1.1 shortly afterwards.

**Comment by fancycode** [comment]
Could you please test the `master` tag from Docker Hub?

**Comment by Chartman123** [comment]
@fancycode Looks good, thank you for the quick fix!
