### ISSUE TITLE
Endless loop of renew sessions with Talk 9.0.3

### ISSUE THREAD

**Issue by markuman** [strukturag/nextcloud-spreed-signaling#43]
I got a working nats, Janus, coturn, spreed signaling setup with Nextcloud 18 and Talk 8.x.  
I turned it off because there was no need atm.

Now on Nextcloud 19 und Talk 9, I turned it on again and it seems that it doesn't work anymore.

The video call sessions are reloading, reloading, reloading ...so all people left and join and left and join ...   
So it is unuseable. 

I'm not sure if it is related to Janus (0.9.2 in the docker setup of this repository). Because in the latest 9.0.3 Talk update, it is mentioned to work with Janu 0.10.4  
https://github.com/nextcloud/spreed/releases/tag/v9.0.3

Janus  logs

```
...
[WARN] Subscriber is using the legacy 'listener' ptype
[8937183532198227] Creating ICE agent (ICE Full mode, controlling)
Creating new handle in session 8379557828949997: 1992690372055633; 0x5646f2b3d1a0 0x5646f2b868c0
Creating new handle in session 8379557828949997: 6144606228744884; 0x5646f2b3d1a0 0x5646f2b92ae0
[1992690372055633] Creating ICE agent (ICE Full mode, controlled)
[WARN] Subscriber is using the legacy 'listener' ptype
[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:5710] No such feed (1)
Detaching handle from JANUS VideoRoom plugin; 0x5646f2b92ae0 0x5646f2b55e20 0x5646f2b92ae0 0x5646f2b6a820
...
```

spreed signaling

```
2020/08/25 17:57:53.896305 hub.go:1306: Could not send MCU message &{Type:requestoffer Sid: RoomType:video Payload:map[]} for session bY71yyYqeklh4F-Z_3jmCmjNeuCV4yj-cRaMiSWpCMp8QXVqbHdnTWRSSnJidTdlTDc1bkJ0UGJFRVZvMnhla3prRjVfdTBXeEwzRzlEVUdSLUhZSENYV0tTM2RpQVh0S2ZYWnNxYW9GMGVxR1RhN0tQZDRzd2M5Z0NiSFZyT0ItV0RnVVZHbkNEWW9JVER1X0VEQ0FFc2xNb3pUTUFfMnNXYjFqSFFCWGVPbGV8NjUyODczODk1MQ== to 6aKQdqqv0n-Hz1ymBvgocqBPXojeukSqMAmNHX0O-Vh8eGlnR2I0UEozN29iTEptTjEza1AyY0d6YlNaeHBESklQTnlLaUJxNVJKMThNVFI4SWc3SDVQclJIaXlxOUhGUmR6NHlha0ZEVWE5aS1qZDZIQnNqNlgyUTZtX2hqelE2Sk1QUFVZdWlxUGdvNWt5d0haWjhCbm45TFRWc3hQM080RUhVMWltTmlXaTV8MzYyODczODk1MQ==: context deadline exceeded
```

**Comment by markuman** [comment]
maybe https://github.com/nextcloud/spreed/pull/4069

**Comment by maxbax0808** [comment]
I am having the same Issue with the Docker-Version. Using Nextcloud 20 (also in docker) and Talk Version 10.0.5.
I have practically the same Errors in the logs, but I am missing the Error from the spreedbackend container...

**Comment by fancycode** [comment]
Sorry for the late reply, does this still happen with the latest version?

**Comment by fancycode** [comment]
Feel free to reopen if this still happens with the latest version / master branch.
