### ISSUE TITLE
Broken build after upgrade to v1.1.1

### ISSUE THREAD

**Issue by mmallejac** [strukturag/nextcloud-spreed-signaling#431]
Hello !

I've noticed a new release so I wanted to build it, but unfortunately:

```[+] Building 0.1s (4/4) FINISHED
 => CANCELED [talksignaling-janus internal] load build definition from Dockerfile
 => => transferring dockerfile: 1.56kB
 => CANCELED [talksignaling-janus internal] load .dockerignore
 => => transferring context: 2B                      
 => [talksignaling-spreedbackend internal] load .dockerignore
 => => transferring context: 86B
 => [talksignaling-spreedbackend internal] load build definition from Dockerfile
 => => transferring dockerfile: 2B
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount306945275/Dockerfile: no such file or directory
```

I've also noticed that the image is available here : https://hub.docker.com/r/strukturag/nextcloud-spreed-signaling
Using this image instead of building it locally works fine, but just wanted to let you know about it.

**Comment by fancycode** [comment]
Not sure how you are building, but the `Dockerfile` has moved to a subfolder in recent releases:
https://github.com/strukturag/nextcloud-spreed-signaling/tree/master/docker/server
https://github.com/strukturag/nextcloud-spreed-signaling/tree/master/docker/proxy

But using the official image is perfectly fine, too.
