### ISSUE TITLE
In the 1.1.2 version, the 'latest' docker image is pointing to the '-proxy' one

### ISSUE THREAD

**Issue by muchachagrande** [strukturag/nextcloud-spreed-signaling#444]
As the title says, before 1.1.2, the 'latest' image was the Signaling Server.
The recent update, when I pulled the 'latest' image it replaced the server with the proxy.
I had to pull the image using the tag '1.1.2'.

**Comment by fancycode** [comment]
Thanks for the heads up. I updated the `latest` tag manually to point to the signaling server 1.1.2. Starting with the next version, there will be proper `latest` and `latest-proxy` tags (see #445 above).

**Comment by muchachagrande** [comment]
Excelent!! thank you.
