### ISSUE TITLE
Installation don't work

### ISSUE THREAD

**Issue by Jason-Linux** [strukturag/nextcloud-spreed-signaling#457]
Hello

I follow the installation but your makefile don't work for protoc-gen-go

**Comment by fancycode** [comment]
Please provide more information what you are trying to do and on which platform / which version of Go. Also any output / error messages you are getting might help.

**Comment by Jason-Linux** [comment]
Hi I used go in 1.15 and i update to 1.20.2
OS : Debian 11.3
Now i use your actual git insteat of your latest package. Beacause with it don't work.

**Comment by fancycode** [comment]
So it works for recent checkouts? Closing then.
