### ISSUE TITLE
Fehler im log need help

### ISSUE THREAD

**Issue by chris-yooo** [strukturag/nextcloud-spreed-signaling#458]
Grüße

mein signaling will nicht so recht hast du da evtl eine lösung ?

chatten geht
call ob mit oder ohne cam geht nicht

logdatei spuckt das aus:

.... `403 Forbidden` response:\nAuthentication check failed\n\n","Code":403,"Trace":[{"file":"/var/w.....

[nextcloud.log](https://github.com/strukturag/nextcloud-spreed-signaling/files/11165016/nextcloud.log)

screenys:
in rot die cloud von einem freund (dort ist alles IO und geht)

<img width="250px" src="https://user-images.githubusercontent.com/55069641/230145064-515db4ad-0e94-4448-aff2-f2b2ed618774.PNG" />
<img width="250px" src="https://user-images.githubusercontent.com/55069641/230145069-8d0a7b47-e54b-4a4f-9ed9-b779405f85be.PNG" />
<img width="250px" src="https://user-images.githubusercontent.com/55069641/230145073-3420e22f-3ea5-4e04-9901-141f6d301a8c.PNG" />

in blau meine cloud, unterschied die Cloud und Talk version...

!<img width="250px" src="https://user-images.githubusercontent.com/55069641/230145126-1d3d7780-e3f8-4948-8623-f1b16eccd87e.PNG" />
<img width="250px" src="https://user-images.githubusercontent.com/55069641/230145131-7f447a0d-3123-4379-b228-327b63674715.PNG" />
<img width="250px" src="https://user-images.githubusercontent.com/55069641/230145134-2cd97b32-a101-466b-8158-a23b0fe9caa2.PNG" />

ich nutze ispconfig mit apache2 / debian 11
habe mit der neusten go 1.20.3 compiliert

server.conf   (nur zu .txt wegen upload fehler)
[server.conf.txt](https://github.com/strukturag/nextcloud-spreed-signaling/files/11165058/server.conf.txt)

danke im voraus für hilfe

**Comment by SystemKeeper** [comment]
You only have configured one backend, you need one for each instance, if they use the same HPB.

**Comment by chris-yooo** [comment]
i got only 1 backend only the signal.strassow.de - 

the signal.eets.... isnt my server :D

**Comment by SystemKeeper** [comment]
Oh, I thought you wanted to use the same HPB for 2 instances. Sorry.
In that case, can you check that the shared secret is really the same?

**Comment by chris-yooo** [comment]
ja the keys and passphrases were ok :)

therefore

i push these files now the only thing that i remove is the shared for  "signal <-> cloud setting"
i spend a whole day + night and i cant say where the main failure are been ^^

But in short:
turnserver cfg got 7 cmd's and these 7 pieces are enought... are put some more in 4 tuning.
turnserver by the way without CERT so server got only turn without S

janus cfg tuning, testing, yada
fixed logfailure that janus thrown because they missing lua files -> i put these in
(usr/share/lua/5.3/ * ...)

signaling cfg tests und tuning so far as are real

My Server works :)

greetz


FILES:
ispConfig Apache2 rewrite - NATS docker cmd - Cloud-Setting Screeny:
[Apache rewrite-NATS docker-Cloud-Setting.zip](https://github.com/strukturag/nextcloud-spreed-signaling/files/11184604/Apache.rewrite-NATS.docker-Cloud-Setting.zip)

SYSTEMCTL/SERVICE FILES:
[systemctl files.zip](https://github.com/strukturag/nextcloud-spreed-signaling/files/11184583/systemctl.files.zip)

JANUS:
[etc janus.zip](https://github.com/strukturag/nextcloud-spreed-signaling/files/11184580/etc.janus.zip)

[missing lua for janus.zip](https://github.com/strukturag/nextcloud-spreed-signaling/files/11184584/missing.lua.for.janus.zip)

COTURN TURN:
[etc turnserver.zip](https://github.com/strukturag/nextcloud-spreed-signaling/files/11184581/etc.turnserver.zip)

SIGNALING - (compiled with go1.20.3@debian11)
[etc signaling.zip](https://github.com/strukturag/nextcloud-spreed-signaling/files/11184582/etc.signaling.zip)
