### ISSUE TITLE
allowed_ips does not respect subnet

### ISSUE THREAD

**Issue by DrZoidberg09** [strukturag/nextcloud-spreed-signaling#461]
Hi there,
I have deployed the signaling server in an kubernetes environment. Now I want to scrape metrics with prometheus.

For this I understood you need to set the allow_ips to the connect and scrape metrics. 

And here comes the problem: Kubernetes assigns IPs dynamically. Therefore, if I set the IP to the prometheus pod it works. However, I would need to change it manually if the IP changes.

Usually, this should be solvable if I also define the subnet like: 10.0.0.0/8. But this does not work. Is there a way to use the subnet or even a dns record?

Thanks for any help!

**Comment by fancycode** [comment]
This is possible with #448 / #450 (not part of a release yet).
