### ISSUE TITLE
Use of lt-cred-mech in coturn

### ISSUE THREAD

**Issue by morbificagent** [strukturag/nextcloud-spreed-signaling#49]
Hi together,

im trying to get the signaling server working but im having problems with the connection to coturn.
I am already using it for other services with the options:

user=username:password
lt-cred-mech

But here i should use "static-auth-secret=password"

With coturn i cant mix these options.

Is it possible to configure the signaling server to use the lt-cred-mech auth?

**Comment by fancycode** [comment]
This is actually related to configuring TURN in Nextcloud Talk. See https://github.com/nextcloud/spreed/issues/3301 on using username/password for TURN.
