### ISSUE TITLE
failed to establish connection in Talk

### ISSUE THREAD

**Issue by cidk2000** [strukturag/nextcloud-spreed-signaling#508]
In talk web i recieve this error message : 
![Error Message](https://github.com/strukturag/nextcloud-spreed-signaling/assets/106168061/edb92be1-7b6c-4328-9b62-485c93aeb63a)

Talk Admin ui :
![Turn Server Settings](https://github.com/strukturag/nextcloud-spreed-signaling/assets/106168061/219e8a43-6c07-4272-87a0-6f3a188a8831)
*Secret keys erased*  -
In next cloud log : 

![nextcloud logging](https://github.com/strukturag/nextcloud-spreed-signaling/assets/106168061/3983e2e9-1362-4cbd-b0e1-f3c04d62e2a6)

Server  journalctl of Janus and signalling

![Journal of janus and signaling](https://github.com/strukturag/nextcloud-spreed-signaling/assets/106168061/689c4fb1-4551-445a-8922-457ec9bc6c3a)
it appears to connect to signaling but just logs RTT messages  seems to not reach janus 

![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/106168061/d319911b-1b1f-4983-9d0f-a8544f37f765)
Nats server not moved since - incorrect user settings perhaps?

Coturn has not logged anything.

Syslog during janus,signalling, and Nats-server service restarts
[SysLog.txt](https://github.com/strukturag/nextcloud-spreed-signaling/files/11951487/SysLog.txt)

Configuration files : 
[[http].txt](https://github.com/strukturag/nextcloud-spreed-signaling/files/11951519/http.txt) - signalling

Janus config files were based upon a post made here : #343 from the blog 

nextcloud instance in a vm unbuntu 22.04 behind a nat:
Janus,signaling,nats,turn on a external public facing vps using ubuntu 22.04
any pointers to troublshoot the issue further?

**Comment by fancycode** [comment]
Could you please provide the log entries from the start of the signaling server? It looks like your backend configuration is wrong.

There is no `url` setting in the `[backend]` section. Instead it should be something like this:
```
[backend]
backends = mybackend1
...

[mybackend1]
url = https://cloud.domain.tld
secret = the-secret-from-the-talk-admin-settings
...
```

See the example configuration for details:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/6e81becd4ce4e17cc4c4778a4d690f82a31db2af/server.conf.in#L61

**Comment by cidk2000** [comment]
[http]
listen = 127.0.0.1:8080
[https]
[app]
debug = false
[sessions]
hashkey = random hex 16
blockkey = another random hex 16 
[clients]
internalsecret = the-shared-secret-for-internal-clients -  left as is ?
[backend]
allowall = false
timeout = 10
connectionsperhost = 8
url =   my cloud instance 
secret = same as Talk admin ui 
[nats]
url = nats://localhost:4244
[mcu]
type = janus
url = ws://127.0.0.1:8188
[turn]
apikey = api-key in turn 

secret = same as turn secret key 

servers = turn:127.0.0.1:3478?transport=udp,turn:127:0.0.1:3478?transport=tcp
[geoip]
[geoip-overrides]
[continent-overrides]
[stats]
[etcd]
[grpc]

**Comment by fancycode** [comment]
This is your config, not the logs from the start of the signaling server. Still, your config is not correct (see comment above).

**Comment by cidk2000** [comment]
Thank you for correction here is the  journal logs , thank you for taking your time to look at this 

Jul 05 09:56:36 ubuntu signaling[2824]: main.go:133: Starting up version 5cba69686b8804b67f591b9d7d813e077e5edf35/go1.20.5 as pid 2824
Jul 05 09:56:36 ubuntu signaling[2824]: main.go:142: Using a maximum of 2 CPUs
Jul 05 09:56:36 ubuntu signaling[2824]: natsclient.go:108: Connection established to nats://localhost:4244 (NDJ5M3BAX35HYCRZUGBVZTFKPCFGAQWOVHA4JBII7BPQ5AJBDFCN4HSN)
Jul 05 09:56:36 ubuntu signaling[2824]: grpc_common.go:167: WARNING: No GRPC server certificate and/or key configured, running unencrypted
Jul 05 09:56:36 ubuntu signaling[2824]: grpc_common.go:169: WARNING: No GRPC CA configured, expecting unencrypted connections
Jul 05 09:56:36 ubuntu signaling[2824]: hub.go:200: Using a maximum of 8 concurrent backend connections per host
Jul 05 09:56:36 ubuntu signaling[2824]: hub.go:207: Using a timeout of 10s for backend connections
Jul 05 09:56:36 ubuntu signaling[2824]: hub.go:303: Not using GeoIP database
Jul 05 09:56:36 ubuntu signaling[2824]: mcu_janus.go:294: Connected to Janus WebRTC Server 0.11.8 by Meetecho s.r.l.
Jul 05 09:56:36 ubuntu signaling[2824]: mcu_janus.go:300: Found JANUS VideoRoom plugin 0.0.9 by Meetecho s.r.l.
Jul 05 09:56:36 ubuntu signaling[2824]: mcu_janus.go:305: Data channels are supported
Jul 05 09:56:36 ubuntu signaling[2824]: mcu_janus.go:309: Full-Trickle is enabled
Jul 05 09:56:36 ubuntu signaling[2824]: mcu_janus.go:311: Maximum bandwidth 1048576 bits/sec per publishing stream
Jul 05 09:56:36 ubuntu signaling[2824]: mcu_janus.go:312: Maximum bandwidth 2097152 bits/sec per screensharing stream
Jul 05 09:56:36 ubuntu signaling[2824]: mcu_janus.go:318: Created Janus session 6614660596292163
Jul 05 09:56:36 ubuntu signaling[2824]: mcu_janus.go:325: Created Janus handle 522269946167007
Jul 05 09:56:36 ubuntu signaling[2824]: main.go:263: Using janus MCU
Jul 05 09:56:36 ubuntu signaling[2824]: hub.go:385: Using a timeout of 10s for MCU requests
Jul 05 09:56:36 ubuntu signaling[2824]: backend_server.go:95: Using configured TURN API key
Jul 05 09:56:36 ubuntu signaling[2824]: backend_server.go:96: Using configured shared TURN secret
Jul 05 09:56:36 ubuntu signaling[2824]: backend_server.go:98: Adding "turn:127.0.0.1:3478?transport=udp" as TURN server
Jul 05 09:56:36 ubuntu signaling[2824]: backend_server.go:98: Adding "turn:127:0.0.1:3478?transport=tcp" as TURN server
Jul 05 09:56:36 ubuntu signaling[2824]: backend_server.go:111: No IPs configured for the stats endpoint, only allowing access from 127.0.0.1
Jul 05 09:56:36 ubuntu signaling[2824]: main.go:339: Listening on 127.0.0.1:8080

**Comment by cidk2000** [comment]
Thank you for the prompt i took the config  simple as just declaring a backend as the url ...  but you have to declare 
[backend]
backends = 0001

[0001]
# URL of the Nextcloud instance

url =nextloud instance 

# Shared secret for requests from and to the backend servers. This must be the
# same value as configured in the Nextcloud admin ui.
secret = secret id of next ui

**Comment by cidk2000** [comment]
Does this request a re-opening?

still not working correctly for me 

desktop connects to the signalling server i can see the log with the emoticons in it etc.. 
any mobile user recieves or connects to talk i get one line : 
...
: client.go:284: Client from 92.27.138.96 has RTT of 77 ms (77.60026ms)
Jul 06 10:42:51 ubuntu signaling[5545]: capabilities.go:151: Capabilities expired for https://cloud.wh-computers.co.uk/ocs/v2.php/cloud/capabilities, updating
Jul 06 10:42:52 ubuntu signaling[5545]: capabilities.go:214: Received capabilities map[config:map[attachments:map[allowed:false] call:map[breakout-rooms:true can-upload-background:false enabled:true predefined-backgrounds:[1_office.jpg 2_home.jpg 3_abstract.jpg 4_beach.jpg 5_park.jpg 6_theater.jpg 7_library.jpg 8_space_station.jpg] recording:false supported-reactions:[❤️ 🎉 👏 👍 👎 😂 🤩 🤔 😲 😥]] chat:map[max-length:32000 read-privacy:0 translations:[] typing-privacy:0] conversations:map[can-create:false] previews:map[max-gif-size:3.145728e+06] signaling:map[hello-v2-token-key:-----BEGIN PUBLIC KEY-----
Jul 06 10:42:52 ubuntu signaling[5545]: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVKD0oL/yvpEzIxJAsKKRwzGUKkvo
Jul 06 10:42:52 ubuntu signaling[5545]: nLc7qH9x4xKtAeJj14x3XplFBXlFU1l5WZBEPvicCoTrLa/guCZX8wGxdg==
Jul 06 10:42:52 ubuntu signaling[5545]: -----END PUBLIC KEY-----
Jul 06 10:42:52 ubuntu signaling[5545]:  session-ping-limit:200]] features:[audio video chat-v2 conversation-v4 guest-signaling empty-group-room guest-display-names multi-room-users favorites last-room-activity no-ping system-messages delete-messages mention-flag in-call-flags conversation-call-flags notification-levels invite-groups-and-mails locked-one-to-one-rooms read-only-rooms listable-rooms chat-read-marker chat-unread webinary-lobby start-call-flag chat-replies circles-support force-mute sip-support sip-support-nopin chat-read-status phonebook-search raise-hand room-description rich-object-sharing temp-user-avatar-api geo-location-sharing voice-message-sharing signaling-v3 publishing-permissions clear-history direct-mention-flag notification-calls conversation-permissions rich-object-list-media rich-object-delete unified-search chat-permission silent-send silent-call send-call-notification talk-polls breakout-rooms-v1 recording-v1 avatar chat-get-context single-conversation-status chat-keep-notifications typing-privacy message-expiration reactions chat-reference-id] version:17.0.1] from https://cloud.wh-computers.co.uk/ocs/v2.php/cloud/capabilities
Jul 06 10:42:52 ubuntu signaling[5545]: hub.go:740: Register user wayne@0001 from 92.27.138.96 in unknown-country (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0) 8tW8aN64SiIAwDAYBSXrMExDyreNiJP248CQgmV2Oxp8PWNvSHI3QU9zeWFDN012X3lwT3pSYzZRcS1YN1ZmRGNnU0ZEbHhYWkk4eW1zbllvN2ZITW1oampiY2RWSEZSY0EyUDM2d3o2ZkdMSktkcjkyRUhLa2tpSlNLbE82XzhZd3JoWExENXZCZHA0cUJDcnFka29McURtaTZhMktndjYtLVpTU3VjLUhOTV9mbXV3RU1icG40VG55SktNVnNQUzF4cVlOZFN6fDI3MTA0Njg4NjE= (private=MTY4ODY0MDE3MnxTSXh4WVJaTV81cU5ZMDFpZC1qQ2FrdDI5SVN4VnRfNkU4cF9MeFROTkRwcWhhLS1sNThrUTJVUzhNWkVjVnFBT2dWc0xkZkQxSW9kTFRtSVhRT1cyUXp1MEQxTWJwNURscEVKOUpxVFlsMElxX19NYm1qcU9sRFpQY1hUbm5nWjRlZzRWeGhmeEpFRHBNaXV0T2FGeHVlUnBYWmdPUzZseDR5elJCbz18YCBiGII64Kn_zOyXz4GQu7qxTwktO1EtVdtm07YwNWE=)
Jul 06 10:42:57 ubuntu signaling[5545]: client.go:282: Client ILJ5tcgFtW7RZ9sr7d_kNMzoQKjz0stwc8tAruTwmfx8PVlYTVVxdll3S0xVMGF5TkJOdjBwRDg3TTNTbDBocU5lTTlZMFVlcDhmd002aDRWZVVxTFhKNUc2dXBKQ0wyQm9SZXF2SU5lVUJUcnlJdVB6dEk4V0syZnVtQkgwaEYyZ2hSM3JBQzNLXzV5ei1CMHNNUFUzZzVhSV9EYmxCMnRsOXFhQXdpdk9OQ01xNWNKRXRfWFVUdGtNUXM4cnpUWkNETGF6TUM0fDc4NTUzNjg4NjE= has RTT of 77 ms (77.44854ms)
Jul 06 10:43:04 ubuntu signaling[5545]: mcu_janus.go:729: Attached video as publisher 4343095214566726 to plugin janus.plugin.videoroom in session 8786342088238869
Jul 06 10:43:04 ubuntu signaling[5545]: mcu_janus.go:767: Created room 3613984918651539 {janus.plugin.videoroom map[permanent:false room:3613984918651539 videoroom:created]}
Jul 06 10:43:04 ubuntu signaling[5545]: mcu_janus.go:825: Publisher 8tW8aN64SiIAwDAYBSXrMExDyreNiJP248CQgmV2Oxp8PWNvSHI3QU9zeWFDN012X3lwT3pSYzZRcS1YN1ZmRGNnU0ZEbHhYWkk4eW1zbllvN2ZITW1oampiY2RWSEZSY0EyUDM2d3o2ZkdMSktkcjkyRUhLa2tpSlNLbE82XzhZd3JoWExENXZCZHA0cUJDcnFka29McURtaTZhMktndjYtLVpTU3VjLUhOTV9mbXV3RU1icG40VG55SktNVnNQUzF4cVlOZFN6fDI3MTA0Njg4NjE= is using handle 4343095214566726
Jul 06 10:43:04 ubuntu signaling[5545]: clientsession.go:890: Publishing video as 4 for session 8tW8aN64SiIAwDAYBSXrMExDyreNiJP248CQgmV2Oxp8PWNvSHI3QU9zeWFDN012X3lwT3pSYzZRcS1YN1ZmRGNnU0ZEbHhYWkk4eW1zbllvN2ZITW1oampiY2RWSEZSY0EyUDM2d3o2ZkdMSktkcjkyRUhLa2tpSlNLbE82XzhZd3JoWExENXZCZHA0cUJDcnFka29McURtaTZhMktndjYtLVpTU3VjLUhOTV9mbXV3RU1icG40VG55SktNVnNQUzF4cVlOZFN6fDI3MTA0Njg4NjE=
Jul 06 10:43:04 ubuntu signaling[5545]: janus_client.go:490: Received event for unknown transaction, ignoring: {
Jul 06 10:43:04 ubuntu signaling[5545]:    "janus": "ack",
Jul 06 10:43:04 ubuntu signaling[5545]:    "session_id": 8786342088238869,
Jul 06 10:43:04 ubuntu signaling[5545]:    "transaction": "1559"
Jul 06 10:43:04 ubuntu signaling[5545]: }
Jul 06 10:43:04 ubuntu signaling[5545]: mcu_janus.go:864: Publisher 4343095214566726 received connected
Jul 06 10:43:18 ubuntu signaling[5545]: client.go:284: Client from 92.27.138.96 has RTT of 204 ms (204.383175ms)
Jul 06 10:43:21 ubuntu signaling[5545]: client.go:303: Error reading from 92.27.138.96: read tcp 127.0.0.1:8080->127.0.0.1:41304: use of closed network connection
Jul 06 10:43:40 ubuntu signaling[5545]: mcu_janus.go:854: Publisher 4343095214566726 received hangup (DTLS alert), closing
Jul 06 10:43:40 ubuntu signaling[5545]: mcu_janus.go:922: Room 3613984918651539 destroyed
Jul 06 10:43:45 ubuntu signaling[5545]: client.go:282: Client 8tW8aN64SiIAwDAYBSXrMExDyreNiJP248CQgmV2Oxp8PWNvSHI3QU9zeWFDN012X3lwT3pSYzZRcS1YN1ZmRGNnU0ZEbHhYWkk4eW1zbllvN2ZITW1oampiY2RWSEZSY0EyUDM2d3o2ZkdMSktkcjkyRUhLa2tpSlNLbE82XzhZd3JoWExENXZCZHA0cUJDcnFka29McURtaTZhMktndjYtLVpTU3VjLUhOTV9mbXV3RU1icG40VG55SktNVnNQUzF4cVlOZFN6fDI3MTA0Njg4NjE= has RTT of 76 ms (76.66917ms)
Jul 06 10:43:51 ubuntu signaling[5545]: client.go:282: Client ILJ5tcgFtW7RZ9sr7d_kNMzoQKjz0stwc8tAruTwmfx8PVlYTVVxdll3S0xVMGF5TkJOdjBwRDg3TTNTbDBocU5lTTlZMFVlcDhmd002aDRWZVVxTFhKNUc2dXBKQ0wyQm9SZXF2SU5lVUJUcnlJdVB6dEk4V0syZnVtQkgwaEYyZ2hSM3JBQzNLXzV5ei1CMHNNUFUzZzVhSV9EYmxCMnRsOXFhQXdpdk9OQ01xNWNKRXRfWFVUdGtNUXM4cnpUWkNETGF6TUM0fDc4NTUzNjg4NjE= has RTT of 76 ms (76.913265ms)
Jul 06 10:44:36 ubuntu signaling[5545]: hub.go:832: Unregister 8tW8aN64SiIAwDAYBSXrMExDyreNiJP248CQgmV2Oxp8PWNvSHI3QU9zeWFDN012X3lwT3pSYzZRcS1YN1ZmRGNnU0ZEbHhYWkk4eW1zbllvN2ZITW1oampiY2RWSEZSY0EyUDM2d3o2ZkdMSktkcjkyRUhLa2tpSlNLbE82XzhZd3JoWExENXZCZHA0cUJDcnFka29McURtaTZhMktndjYtLVpTU3VjLUhOTV9mbXV3RU1icG40VG55SktNVnNQUzF4cVlOZFN6fDI3MTA0Njg4NjE= (private=MTY4ODY0MDE3MnxTSXh4WVJaTV81cU5ZMDFpZC1qQ2FrdDI5SVN4VnRfNkU4cF9MeFROTkRwcWhhLS1sNThrUTJVUzhNWkVjVnFBT2dWc0xkZkQxSW9kTFRtSVhRT1cyUXp1MEQxTWJwNURscEVKOUpxVFlsMElxX19NYm1qcU9sRFpQY1hUbm5nWjRlZzRWeGhmeEpFRHBNaXV0T2FGeHVlUnBYWmdPUzZseDR5elJCbz18YCBiGII64Kn_zOyXz4GQu7qxTwktO1EtVdtm07YwNWE=)
Jul 06 10:44:45 ubuntu signaling[5545]: client.go:282: Client ILJ5tcgFtW7RZ9sr7d_kNMzoQKjz0stwc8tAruTwmfx8PVlYTVVxdll3S0xVMGF5TkJOdjBwRDg3TTNTbDBocU5lTTlZMFVlcDhmd002aDRWZVVxTFhKNUc2dXBKQ0wyQm9SZXF2SU5lVUJUcnlJdVB6dEk4V0syZnVtQkgwaEYyZ2hSM3JBQzNLXzV5ei1CMHNNUFUzZzVhSV9EYmxCMnRsOXFhQXdpdk9OQ01xNWNKRXRfWFVUdGtNUXM4cnpUWkNETGF6TUM0fDc4NTUzNjg4NjE= has RTT of 76 ms (76.93841ms)
Jul 06 10:45:02 ubuntu signaling[5545]: hub.go:832: Unregister ILJ5tcgFtW7RZ9sr7d_kNMzoQKjz0stwc8tAruTwmfx8PVlYTVVxdll3S0xVMGF5TkJOdjBwRDg3TTNTbDBocU5lTTlZMFVlcDhmd002aDRWZVVxTFhKNUc2dXBKQ0wyQm9SZXF2SU5lVUJUcnlJdVB6dEk4V0syZnVtQkgwaEYyZ2hSM3JBQzNLXzV5ei1CMHNNUFUzZzVhSV9EYmxCMnRsOXFhQXdpdk9OQ01xNWNKRXRfWFVUdGtNUXM4cnpUWkNETGF6TUM0fDc4NTUzNjg4NjE= (private=MTY4ODYzNTU4N3wwSXprMzJXWWpFV0sxRXZzYlZvQWVLSkZ2MjFZNTRoVUxkUHpGcFREQnlVV09mcjBzdnpUcWhtNVdoUEY2WE5uOTdpTHZBR0dTYlFCVWM1ajVsX1cwcXZFVjJkNG5TbU5BcUJCeHBsSXBhQUNUdXVWdHN2OE5KYXNHQTdyWTEtQWhpTXBsemljbnEwVjI2U3RZNVBwcjBUd1RBSmhyMWJiZGdmeUNxND18rY3TI-RgcVpdPNrGeERQvjA_XKBIKr9Pv0_2Nbt5K4Y=)
Jul 06 10:45:07 ubuntu signaling[5545]: hub.go:585: Closing expired session 8tW8aN64SiIAwDAYBSXrMExDyreNiJP248CQgmV2Oxp8PWNvSHI3QU9zeWFDN012X3lwT3pSYzZRcS1YN1ZmRGNnU0ZEbHhYWkk4eW1zbllvN2ZITW1oampiY2RWSEZSY0EyUDM2d3o2ZkdMSktkcjkyRUhLa2tpSlNLbE82XzhZd3JoWExENXZCZHA0cUJDcnFka29McURtaTZhMktndjYtLVpTU3VjLUhOTV9mbXV3RU1icG40VG55SktNVnNQUzF4cVlOZFN6fDI3MTA0Njg4NjE= (private=MTY4ODY0MDE3MnxTSXh4WVJaTV81cU5ZMDFpZC1qQ2FrdDI5SVN4VnRfNkU4cF9MeFROTkRwcWhhLS1sNThrUTJVUzhNWkVjVnFBT2dWc0xkZkQxSW9kTFRtSVhRT1cyUXp1MEQxTWJwNURscEVKOUpxVFlsMElxX19NYm1qcU9sRFpQY1hUbm5nWjRlZzRWeGhmeEpFRHBNaXV0T2FGeHVlUnBYWmdPUzZseDR5elJCbz18YCBiGII64Kn_zOyXz4GQu7qxTwktO1EtVdtm07YwNWE=)
Jul 06 10:45:08 ubuntu signaling[5545]: client.go:284: Client from 92.40.198.238 has RTT of 267 ms (267.96511ms)
Jul 06 10:45:10 ubuntu signaling[5545]: client.go:303: Error reading from 92.40.198.238: read tcp 127.0.0.1:8080->127.0.0.1:52496: use of closed network connection
Jul 06 10:47:12 ubuntu signaling[5545]: client.go:284: Client from 92.27.138.96 has RTT of 77 ms (77.403991ms)
...
client.go:303: Error reading from 92.27.138.96: read tcp 127.0.0.1:8080->127.0.0.1:41304: use of closed network connection

pfsense>nginx reverse proxy>nextcloud nginx  

Andrioid APP latest is used for the use of closed network connectionn

**Comment by fancycode** [comment]
> Does this request a re-opening?
> 
> still not working correctly for me
[...]
> pfsense>nginx reverse proxy>nextcloud nginx
> 
> Andrioid APP latest is used for the use of closed network connectionn

Unfortunately not. This is related to something in front of the signaling server closing the connection too early. Maybe your pfsense / nginx logs will show more information.  If it's working in the browser, then the signaling server setup itself is correct.
