### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input  at JSON.parse (<anonymous>)  at y.<anonymous> (signaling.js:722:16)

### ISSUE THREAD

**Issue by MorganReid** [strukturag/nextcloud-spreed-signaling#509]
According to README.md. I installed nextcloud-spreed-signaling (Running as daemon), the following is my configuration file:
![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/52235796/f3c843dd-af90-46b7-9d9a-0ad936ecba58)
This is the nginx configuration for nextcloud-spreed-signaling:
![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/52235796/ed22ed41-350e-434b-bb52-706a9fe745db)
Then my configuration in nextcloud talk (desktop) is as follows:
![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/52235796/a48b9a15-6a90-4369-9dbe-25cd3b684fed)
Finally, when I click on a specific member in Talk, the browser's console information reports an error as follows:
![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/52235796/ea68ddd8-c218-48a4-8860-66b0641a60ba)
It is normal to visit `https://mailtest.autox.sz:3443/standalone-signaling/api/v1/welcome`:
![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/52235796/dfefd7cf-ca38-4187-994f-e98810d405ac)

Do you have any good suggestions? In addition, where can I view the logs corresponding to this service? Very much looking forward to receiving your reply.

**Comment by fancycode** [comment]
Most likely this is the same as #180. If you are running the service as systemd daemon, you (usually) should find the logs in the journal (see `man journalctl`).
