### ISSUE TITLE
snap version (question)

### ISSUE THREAD

**Issue by theoneandonly-vector** [strukturag/nextcloud-spreed-signaling#51]
will this be in the snap-version in the future?

**Comment by szaimen** [comment]
Please look at this thread:
https://help.nextcloud.com/t/nextcloud-talk-signaling-server-now-automated-installation/90567/57
I think this should answer your question.

**Comment by theoneandonly-vector** [comment]
@szaimen I don't think so (at least I didn't found any announcement / decline for an official snap-version of nextcloud-spreed-signaling)

In the discussion you linked they talked about including it inside nextclouds snap.. what only would make sense if there is a Nextcloud Hub snap.

But I ask for it's own snap.

**Comment by szaimen** [comment]
> But I ask for it's own snap.

@theoneandonly-vector Okay, thanks for the clarification!

**Comment by fancycode** [comment]
We currently don't plan to provide a snap version. If someone from the community wants to do that and changes are required, feel free to open pull-requests.
