### ISSUE TITLE
lt-cred-mech invalid with 

### ISSUE THREAD

**Issue by BrownofCony** [strukturag/nextcloud-spreed-signaling#516]
hi，i wanna to use coturn with lt-cred-mech during stun-only mode ;but when i test without user and password; turnserver response; so what's wrong with it ?

details are as follows：
a. turnadmin add user (with realm  user passsword)

b.start turnserver with the following conf:
`listening-port=3478
alt-listening-port=3479
lt-cred-mech
stun-only
no-tcp
no-tls
user=admin:0xd4a0dc827b45e228c6ebaa051c2ab488
realm=com.dirtybear
verbose
secure-stun`

c.start stun_client with command line 'turnutils_uclient -p 3478 -v [myip] -y'

**Comment by fancycode** [comment]
Not sure how this is related to the signaling server?
If it's a issue regarding the setup / use of Coturn, it should be reported there: https://github.com/coturn/coturn
