### ISSUE TITLE
crypto/ecdh Go package issue 

### ISSUE THREAD

**Issue by InnovateFusionLLC** [strukturag/nextcloud-spreed-signaling#517]
As far as I can tell the Go standard library doesn't have a package named crypto/ecdh. So when I attempt to Make Build I am running into the following error....

PATH="/usr/bin":/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin "/root/go/bin/easyjson" -all api_proxy.go
build command-line-arguments: cannot load crypto/ecdh: malformed module path "crypto/ecdh": missing dot in first path element
Bootstrap failed: exit status 1
make: *** [Makefile:105: api_proxy_easyjson.go] Error 1

Admittedly, I am a novice at this stuff so I am probably not doing sorting correct. However, I did make sure I have all the dependancies installed and running. 

Any clue how to fixe this? It these an easier way to get a TURN server running / configured for NextCloud running in a VM on Proxmox using Cloudflare tunnel to connect to a Cloudflare domain. I would think I could count the video and audio traffic through the existing tunnel some how.

**Comment by fancycode** [comment]
`crypto/ecdh` is part of the standard library: https://pkg.go.dev/crypto/ecdh

What version of Go on which platform are you using?

The signaling server doesn't provide TURN, if you are looking for this, you should check out Coturn at https://github.com/coturn/coturn instead.

**Comment by LaserGrunt** [comment]
I am am trying to run this in addition to coturn. 
System=MOGINSOK 2.5GbE Linux Firewall Micro Appliance Celeron N5105 4xIntel I226 Nic Firewall Router PC 
OS=PROXMOX
VM1=Turnkey-Nextcloud
VM2=Debian latests ... Cloudfrlared, Coturn, and this
I am trying to add a HAB however, I think I am now understanding this is just a portion of it.

**Comment by fancycode** [comment]
Still didn't answer which version of Go you are running. Please post the output of `go version` and `go env`.

Most likely it's a version of Go older than 1.20 which is not supported.

**Comment by fancycode** [comment]
If this still happens with the latest version (and a supported version of Go), feel free to reopen with more feedback.
