### ISSUE TITLE
GuzzleHttp\Exception\ClientException : Erreur client : POST https://signalingserver.domain.com/standalone-signaling/api/v1/room/imx8frtt a entraîné une réponse 403 Forbidden : La vérification de l'authentification a échoué

### ISSUE THREAD

**Issue by uruzFR** [strukturag/nextcloud-spreed-signaling#527]
Hello !

i have this error in **Nextcloud logs :** 

GuzzleHttp\Exception\ClientException  : Erreur client : POST https://signalingserver.domain.com/standalone-signaling/api/v1/room/imx8frtt a entraîné une réponse 403 Forbidden : La vérification de l'authentification a échoué

**Signalings logs :**

oiko@sssl:~/nextcloud-spreed-signaling$ sudo ./bin/signaling --config /etc/signaling/server.conf
[sudo] password for oiko: 
main.go:133: Starting up version 8bf0b53d0bb32dbc38b6cdb73655cc073cbb98c3/go1.18.1 as pid 1402
main.go:142: Using a maximum of 1 CPUs
natsclient.go:108: Connection established to nats://localhost:4222
grpc_common.go:167: WARNING: No GRPC server certificate and/or key configured, running unencrypted
grpc_common.go:169: WARNING: No GRPC CA configured, expecting unencrypted connections
hub.go:200: Using a maximum of 8 concurrent backend connections per host
hub.go:207: Using a timeout of 10s for backend connections
hub.go:303: Not using GeoIP database
main.go:193: WARNING: Old-style MCU configuration detected with url but no type, defaulting to type janus
mcu_janus.go:294: Connected to Janus WebRTC Server 0.11.8 by Meetecho s.r.l.
mcu_janus.go:300: Found JANUS VideoRoom plugin 0.0.9 by Meetecho s.r.l.
mcu_janus.go:305: Data channels are supported
mcu_janus.go:309: Full-Trickle is enabled
mcu_janus.go:311: Maximum bandwidth 1048576 bits/sec per publishing stream
mcu_janus.go:312: Maximum bandwidth 2097152 bits/sec per screensharing stream
mcu_janus.go:318: Created Janus session 6537124536058702
mcu_janus.go:325: Created Janus handle 8971974268218711
main.go:263: Using janus MCU
hub.go:385: Using a timeout of 10s for MCU requests
backend_server.go:95: Using configured TURN API key
backend_server.go:96: Using configured shared TURN secret
backend_server.go:98: Adding "turn:cloud.domain.com:3478?transport=udp" as TURN server
backend_server.go:98: Adding "turn:cloud.domain.com:3478?transport=tcp" as TURN server
backend_server.go:111: No IPs configured for the stats endpoint, only allowing access from 127.0.0.1
main.go:339: Listening on 127.0.0.1:8080
client.go:284: Client from XX.XX.XX.XX has RTT of 51 ms (51.176132ms)
client.go:284: Client from XX.XX.XX.XX has RTT of 64 ms (64.287484ms)
client.go:284: Client from XX.XX.XX.XX has RTT of 231 ms (231.87662ms)
client.go:284: Client from XX.XX.XX.XX has RTT of 96 ms (96.033098ms)
client.go:284: Client from XX.XX.XX.XX has RTT of 44 ms (44.874561ms)
client.go:284: Client from XX.XX.XX.XX has RTT of 133 ms (133.495209ms)
client.go:284: Client from XX.XX.XX.XX has RTT of 69 ms (69.191126ms)
client.go:284: Client from XX.XX.XX.XX has RTT of 64 ms (64.574188ms)
client.go:284: Client from XX.XX.XX.XX has RTT of 68 ms (68.120593ms)
client.go:284: Client from XX.XX.XX.XX has RTT of 119 ms (119.176912ms)
client.go:303: Error reading from XX.XX.XX.XX: websocket: close 1006 (abnormal closure): unexpected EOF
**^C**main.go:362: Interrupted
janus_client.go:470: Unable to deliver message {
   "janus": "detached",
   "session_id": 6537124536058702,
   "sender": 8971974268218711
}. Handle 8971974268218711 gone?
janus_client.go:405: conn.NextReader: read tcp 127.0.0.1:49700->127.0.0.1:8188: use of closed network connection
mcu_janus.go:271: Connection to Janus gateway was interrupted, reconnecting in 1s

![Capture d’écran 2023-08-02 à 22 37 43](https://github.com/strukturag/nextcloud-spreed-signaling/assets/111280713/082fe746-c647-49bb-9771-173602c8fc02)

**Conf file :**
[server.txt](https://github.com/strukturag/nextcloud-spreed-signaling/files/12244476/server.txt)

_Originally posted by @uruzFR in https://github.com/strukturag/nextcloud-spreed-signaling/issues/141#issuecomment-1662953444_

**Comment by fancycode** [comment]
Your server configuration is incomplete. You have to enable the list of `backends`:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/65209deb7d32933d31acdffba506941e92756d5d/server.conf.in#L67

Also you need to put your `url` / `secret` in a section matching the backend id configured:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/65209deb7d32933d31acdffba506941e92756d5d/server.conf.in#L108

I'll check if I can add a warning during startup when no backends are configured properly.

**Comment by uruzFR** [comment]
Thank you very much for your help 👍🏻
