### ISSUE TITLE
Incomplete OCS response

### ISSUE THREAD

**Issue by surfparadise** [strukturag/nextcloud-spreed-signaling#535]
I still continue to try to setup a signaling server, without success.

I follow this tutorial: https://markus-blog.de/index.php/2020/07/30/how-to-install-nextcloud-talk-high-performance-backend-with-stun-turnserver-on-ubuntu/

I can establish a correct connection into the TALK configuration backend, but when I create a room, I have errors. 
Into my vm iI have this behaviours:

curl -i https://signaling.mydomain.com/standalone-signaling/api/v1/welcome

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Server: nextcloud-spreed-signaling/e427d0daa6640021e31b6b253e065c7240fb3613
X-Spreed-Signaling-Features: audio-video-permissions, hello-v2, incall-all, mcu, simulcast, switchto, transient-data, update-sdp, welcome
Date: Tue, 08 Aug 2023 10:16:55 GMT
Content-Length: 94

curl -i https://signaling.mydomain.com/standalone-signaling/api/v1/room/cgu2w45c
HTTP/2 405 
server: nginx/1.18.0 (Ubuntu)
date: Wed, 09 Aug 2023 09:39:31 GMT
content-length: 0

------------------------------------------------------------------------------

● signaling.service - Nextcloud Talk signaling server
     Loaded: loaded (/etc/systemd/system/signaling.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-08-09 11:29:51 CEST; 10min ago
   Main PID: 905 (signaling)
      Tasks: 8 (limit: 1050)
     Memory: 27.9M
     CGroup: /system.slice/signaling.service
             └─905 /usr/bin/signaling --config /etc/signaling/server.conf

Aug 09 11:39:51 amd signaling[905]: capabilities.go:192: **Incomplete OCS response** {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":27,"minor":0,"micro":1,"string":"27.>
Aug 09 11:39:51 amd signaling[905]: capabilities.go:248: **Could not get capabilities for** https://my.domain.com/ocs/v2.php/apps/spreed/api/v3/signaling/backend: **incomplete OCS response**
Aug 09 11:39:52 amd signaling[905]: client.go:284: Client from 91.243.138.225 has RTT of 39 ms (39.53753ms)
Aug 09 11:39:52 amd signaling[905]: capabilities.go:151: **Capabilities expired for** https://my.domain.com/ocs/v2.php/cloud/capabilities, updating

---------------------------------------------------------------

ubuntu@amd:~$ sudo systemctl status janus
● janus.service - Janus WebRTC gateway
     Loaded: loaded (/lib/systemd/system/janus.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-08-09 11:29:51 CEST; 18min ago
       Docs: https://janus.conf.meetecho.com/docs/index.html
   Main PID: 904 (janus)
      Tasks: 32 (limit: 1050)
     Memory: 16.7M
     CGroup: /system.slice/janus.service
             └─904 /usr/bin/janus -o

Aug 09 11:29:52 amd janus[904]: Loading transport plugin 'libjanus_websockets.so'...
Aug 09 11:29:52 amd janus[904]: libwebsockets logging: 0
Aug 09 11:29:52 amd janus[904]: WebSockets server started (port 8188)...
Aug 09 11:29:52 amd janus[904]: [WARN] Secure WebSockets server disabled
Aug 09 11:29:52 amd janus[904]: [WARN] Admin WebSockets server disabled
Aug 09 11:29:52 amd janus[904]: [WARN] Secure Admin WebSockets server disabled
Aug 09 11:29:52 amd janus[904]: JANUS WebSockets transport plugin initialized!
Aug 09 11:29:52 amd janus[904]: WebSockets thread started
Aug 09 11:29:53 amd janus[904]: Creating new session: 630177187434718; 0x7f8f14001a70
Aug 09 11:29:53 amd janus[904]: Creating new handle in session 630177187434718: 2409453716119087; 0x7f8f14001a70 0x7f8f14003fd0

--------------------------------------------------------

ubuntu@signaling:~$ sudo nano /etc/signaling/server.conf

[http]
listen = 0.0.0.0:8080
[app]
debug = false

[sessions]
hashkey = xxxxxxxxxx
blockkey = xxxxxxxxxxxx

[backend]
backends = backend-1,
allowall = false
timeout = 10
connectionsperhost = 8

[backend-1]
url = https://mynexcloud.domain
secret = xxxxxxxxxxxxxx

#[backend-2]
#url = https://nextcloud2.example.com
#secret = openssl rand -hex 16

#[backend-3]
#url = https://nextcloud3.example.com
#secret = openssl rand -hex 16

[nats]
url = nats://my_external_nats:4222

[mcu]
type = janus
url = ws://127.0.0.1:8188

[turn]
apikey = xxxxxxx
secret = xxxxxxxxxxxx
servers = turn:my_external_turn_server:3478?transport=udp,turn:my_external_turn_server:3478?transport=tcp

--------------------------------------------

Someone could give me some advice?
(Currently I have not configured any reverse proxy. I point directly to 8080 port of my signaling server)

**Comment by fancycode** [comment]
Sorry for the late response. This indeed looks incomplete:
> Aug 09 11:39:51 amd signaling[905]: capabilities.go:192: Incomplete OCS response {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":27,"minor":0,"micro":1,"string":"27.>

Or was this clipped while copying the output to the issue?

**Comment by fancycode** [comment]
If this is still happening with the latest version, please reopen the issue and provide the full logs.
