### ISSUE TITLE
Nextcloud Talk not connecting to Signaling Server

### ISSUE THREAD

**Issue by VainExpert** [strukturag/nextcloud-spreed-signaling#579]
My Nextcloud Talk won't connect to the signaling server in the Talk UI. In the administrator settings everything is fine with the exception of not showing the Version (Unknown Version). I instaled the latest release 1.1.3.
The specific error message is that the Token is invalid because the context deadline is exceeded.

You got any idea where this error is coming from? Is it a problem that my signaling server and nextcloud are on the same ip and their servers are behind a NAT?
If I should provide my logs and configuration file or any oher information about the setup for more context just tell me.

**Comment by fancycode** [comment]
Please make sure that both servers can access each other (you can test this with `curl`).

**Comment by VainExpert** [comment]
Oh thank you. 
Checked that in one direction and not the other and as it were the other direction didnt work because of firewall restrictions. Changed that now and everything is working smoothly.
Thank you for the hint!
