### ISSUE TITLE
mcu_janus.go: many lost Janus packages

### ISSUE THREAD

**Issue by michikmm** [strukturag/nextcloud-spreed-signaling#59]
I've problems to get Nextcloud Talk running smoothly with High Performance Backend.
First my setup:

* Nextcloud 19.0.4, Talk 9.0.5 (also tested 20.0.1 Talk 10.0.1)
* Ubuntu 20.04.1 LTS
* janus gateway 0.10.9 (also tested 0.10.7, 0.10.4, 0.10.1, 0.9.5)
* nextcloud-spreed-signaling version 9206a56113064b8e44b0de12d5128f8e88617679/go1.13.8
* nats docker latest
* coturn 4.5.1.1-1
* libSRTP2-1_2.3.0-4

I've setup the HPB with the tutorial from https://decatec.de/home-server/nextcloud-talk-mit-eigenem-signaling-server-high-performance-backend/ 

Here my problem:
The call is running fine until someone is starting to share a screen. From there all video streams are freezing until the screenshare is not stopped. 
In signaling log i can see many entries like:

    Nov 12 12:37:58 myhostname signaling[1789]: mcu_janus.go:1012: Subscriber _Tx-QfEhFjvhSFiOnUI2LZnFXscJY7RlRZiIkLepDgZ8aHVDRVotaG5SWkwwaVdYRkhDU0UyVVhXQ2ZhS0phcnFaVVFLdWcteU9maEN5S1VyRnJOeW9pd1l1Y0hPR0QwZlIzbEszd2Z6aUEweXh1d05YWXBGYVFoZlFkalN5b2x3ZHBkM2E5X1cwdkNBdDdaVHJ3ZHZMWTNMaWdlTXpkM01ZQnBJZkJNcTc4VVBWek1qWkdrV0ZQelJwcnpWeTZUYTRTQl95cDl4fDEwNDI4MTUwNjE= (5814447515383452) is reporting 39 lost packets on the uplink (Janus -> client)
    Nov 12 12:37:58 myhostname signaling[1789]: mcu_janus.go:725: Publisher _Tx-QfEhFjvhSFiOnUI2LZnFXscJY7RlRZiIkLepDgZ8aHVDRVotaG5SWkwwaVdYRkhDU0UyVVhXQ2ZhS0phcnFaVVFLdWcteU9maEN5S1VyRnJOeW9pd1l1Y0hPR0QwZlIzbEszd2Z6aUEweXh1d05YWXBGYVFoZlFkalN5b2x3ZHBkM2E5X1cwdkNBdDdaVHJ3ZHZMWTNMaWdlTXpkM01ZQnBJZkJNcTc4VVBWek1qWkdrV0ZQelJwcnpWeTZUYTRTQl95cDl4fDEwNDI4MTUwNjE= (7157238091411248) is reporting 14 lost packets on the downlink (client -> Janus)

All other log files are fine.
I tried a lot of stuff:

* disable ufw on signaling server
* allow all traffic between signaling server an internet (DMZ), no firewalling between
* test multiple browsers / clients
* client's and server's CPU/Network/Ram is easy going
* other versions of janus-gateway

Here my configs:
/etc/turnserver.conf

    listening-port=3478
    tls-listening-port=5349
    min-port=49152
    max-port=65535
    fingerprint
    lt-cred-mech
    use-auth-secret
    static-auth-secret=secret
    realm=mydomain.de
    total-quota=100
    bps-capacity=0
    stale-nonce=600
    cert=/etc/ssl/certs/cer.cer
    pkey=/etc/ssl/private/key.key
    cipher-list="ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384″
    no-stdout-log
    syslog
    no-multicast-peers
    no-tlsv1
    no-tlsv1_1

/etc/janus/janus.jcfg (shortened)

    media: {
            ipv6 = false
            rtp_port_range = "20000-40000"
    }
    nat: {
            stun_server = "signaling.mydomain.de"
            stun_port = 5349
            nice_debug = false
            full_trickle = true
            turn_server = "signaling.mydomain.de"
            turn_port = 5349
            turn_rest_api_key = "secret"
    }

/etc/signaling/server.conf

    [http]
    listen = 127.0.0.1:8080
    [https]
    listen = 127.0.0.1:8443
    certificate = /etc/ssl/certs/cer.cer
    key = /etc/ssl/private/key.key
    [app]
    debug = false
    [sessions]
    hashkey = secret
    blockkey = secret
    [clients]
    internalsecret = secret
    [backend]
    backends = cloud, testcloud
    allowall = false
    secret = secret
    timeout = 10
    connectionsperhost = 8
    [cloud]
    url = https://cloud.mydomain.de
    secret = secret
    [testcloud]
    url = https://testcloud.mydomain.de
    secret = secret
    [nats]
    url = nats://localhost:4222
    [mcu]
    type = janus
    url = ws://127.0.0.1:8188
    [turn]
    apikey = secret
    secret = secret
    servers = turn:signaling.mydomain.de:5349?transport=udp,turn:signaling.mydomain.de:5349?transport=tcp
    [geoip]
    [geoip-overrides]
    [stats]

Best regards
Michael

**Comment by michikmm** [comment]
Note: Without HPB (no signaling server configured) Talk work’s perfectly till there are not more than 4 partipicants…

**Comment by fancycode** [comment]
The message in the signaling server is telling the problem: packets between the clients and the Janus server are lost. 

Screensharing usually requires more bandwidth than regular video streams, so if the server or the clients don't have enough bandwidth, there will be packet loss.

**Comment by michikmm** [comment]
Hi Fancycode,
thanks for your reply.

Bandwith is not the problem (Client is on same esxi host - it's a 10Gbit/s connection between client and server).
Client and server are showing round about 3 Mbit/s traffic - with sreen sharing it increases to 6 Mbit/s

**Comment by Chartman123** [comment]
I just tried to reproduce the log messages, but the only time I saw some lost packets, was when I tried to establish a call with the mobile Android app. But this might be related to another Android Talk app issue...

**Comment by fancycode** [comment]
If you can rule out connectivity issues, best probably would be to open an issue in the Janus repository at https://github.com/meetecho/janus-gateway

The signaling server only does the signaling, but not the actual media relay.
