### ISSUE TITLE
signaling: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by signaling)

### ISSUE THREAD

**Issue by francoisPE** [strukturag/nextcloud-spreed-signaling#598]
Hello,

I am running nextcloud-spreed-signaling for several month and everything was good up to 1.20 release.
Now, I have that messages:
```
signaling: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by signaling)
signaling: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by signaling)
```
I am running ubuntu 20.04 and I don't see how I can upgrade to that versions of GLIBC.

thank you for your help
FrancoisPE

**Comment by francoisPE** [comment]
Would it be possible to push v1.1.3.deb in order to be able to downgrade.
Currently 
```
apt policy nextcloud-spreed-signaling
nextcloud-spreed-signaling:
  Installed: 1.2.0+1
  Candidate: 1.2.0+1
  Version table:
 *** 1.2.0+1 500
        500 https://packaging.gitlab.io/nextcloud-spreed-signaling signaling/main amd64 Packages
        100 /var/lib/dpkg/status
```
No way to downgrade !

**Comment by fancycode** [comment]
These packages are not provided by us, please open an issue in the corresponding repository:
https://gitlab.com/packaging/nextcloud-spreed-signaling

**Comment by francoisPE** [comment]
Hello
Thanks for your reply.
I'll see with other group for pckage downgrade

I didn't see a compatibilty requirement in your presentation.
Nevertheless it seems that 1.2.0 is incompatible with ubuntu 20.04
Is this something you confirm?
You definitely decide to stop running signaling on ubuntu 20.04 ?

**Comment by fancycode** [comment]
No, this depends on how the binary is built. The signaling server itself has no direct dependencies on the OS. All versions surely run fine on Ubuntu 20.04.

**Comment by francoisPE** [comment]
Understood!
I'll see this with morph27
