### ISSUE TITLE
Include version on docker image

### ISSUE THREAD

**Issue by SystemKeeper** [strukturag/nextcloud-spreed-signaling#601]
It would be nice if the docker image could also report the version it was build from instead of the commit hash. For support reasons I would suggest to have it differ slightly from the HPB repo, so instead of displaying „1.1.2“ something like „1.1.2-docker“ (or the like) would be nice.

**Comment by fancycode** [comment]
The version instead of the commit hash should already be there since 1.2.0 (see #584). I'll look at adding `docker` or something similar for a future version.

Unfortunately this closely missed 1.2.1 which was just released.

**Comment by SystemKeeper** [comment]
Oh great, I didn’t catch that in the changelog.

> Unfortunately this closely missed 1.2.1 which was just released.

indeed when I saw the release, it popped up in my mind again, that’s why I created the issue.
