### ISSUE TITLE
"Your internet connection or computer are busy and other participants might be unable to understand you and see your screen. "

### ISSUE THREAD

**Issue by RichardHausgartner** [strukturag/nextcloud-spreed-signaling#616]
I'm using Nextcloud Talk 17.1.3 (in Nextcloud 27.1.4) with the latest nextcloud-speed-signaling code (https://github.com/strukturag/nextcloud-spreed-signaling/commit/9c0e0ba85d8f17e9f47ae33391c414fdb6764ca5)

When sharing my screen with others, I receive a alert window at Nextcloud Talk:

>Your internet connection or computer are busy and other participants might be unable to understand you and see your screen. To improve the situation try to disable your screenshare.

I have the impression that the image quality of the camera and screen sharing is far too good.
How can I reduce this?

(With the signaling server integrated in Nextcloud, the image quality was worse, but sufficient. I never received this alert there).

**Comment by fancycode** [comment]
You can limit the maximum allowed bandwidth in the configuration:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/c85b31bd2437419fd1df1f2e3f870a213fd06c06/server.conf.in#L122-L128
