### ISSUE TITLE
docker-compose: ports are only exportet to localhost

### ISSUE THREAD

**Issue by AlterDepp** [strukturag/nextcloud-spreed-signaling#64]
My nginx-reverse-proxy is on another machine than the signaling server, which I try to run via the provided docker-compose file. So I can not use `proxy_pass http://localhost:8080`, I have to use `proxy_pass http://nano:8080`. With my other docker-compose environmets, this works well, but not with the nextcloud-spreed-signaling server.

The container is up and running on my machine _nano_, I can test it with 
`curl -i http://localhost:8080/api/v1/welcome`
But when I try to use the machine name or ip-address:
`curl -i http://nano:8080/api/v1/welcome`
`curl -i http://192.168.0.2:8080/api/v1/welcome`
I only get
`curl: (7) Failed to connect to nano port 8080: connection refused`

I think, the ports are not exposed correctly.

Stefan

**Comment by christiansicari** [comment]
in Docker-Compose all containers use the network host, thus all the port are mapped.

I may try to stop the HPB and run a simply HTTP server
`docker run --rm -p 8080:80 httpd`

Next,  I will try to curl the server, from the machine where you run Nginx 
`curl -i http://192.168.0.2:8080`
Httpd should reply, if not there is a network problem and not a HPB problem

**Comment by AlterDepp** [comment]
Ok, so I think, it’s a configuration problem, In _server,conf_, I changed
```
[http]
listen = 127.0.0.1:8080
```
to
```
[http]
listen = moma:8080
```
Now I can connect to `192.168.0.2:8080` which is the ip of `moma`,
So how do I change the configuration, so I can connect to `moma:8080`?

**Comment by christiansicari** [comment]
Try 0.0.0.0:8080On Dec 8, 2020 7:58 PM, AlterDepp <notifications@github.com> wrote:

Ok, so I think, it’s a configuration problem, In server,conf, I changed

[http]

listen = 127.0.0.1:8080



to

[http]

listen = moma:8080



Now I can connect to 192.168.0.2:8080 which is the ip of moma,

So how do I change the configuration, so I can connect to moma:8080?

**Comment by AlterDepp** [comment]
Thanks,
now I can access the server from outside by name or ip:
```
[http]
listen = 0.0.0.0:8080
```
