### ISSUE TITLE
Errors from MarshalJSON *signaling.AsyncMessage: unexpected end of JSON input

### ISSUE THREAD

**Issue by tecycloud** [strukturag/nextcloud-spreed-signaling#642]
I set up the high performance backend. But I always get errors from MarshalJSON.

```
[...]
backend_server.go:855: Error processing {"type":"message","message":{"data":{"type":"chat","chat":{"refresh":true}}}} for room a8qnhdzk: json: error calling MarshalJSON for type *signaling.AsyncMessage: unexpected end of JSON input
[...]
```

```
[...]
room.go:561: Could not publish session left message in room vvdqzjy9: json: error calling MarshalJSON for type *signaling.AsyncMessage: unexpected end of JSON input
[...]
```

Does anyone have any idea where this error is coming from?

**Comment by SaadYasir** [comment]
I had the same issue. when you build there are two files in bin proxy and signaling. I simply changed the ownership for both to the user (the one which is configured in systemd for the service), and it worked.

**Comment by Simthem** [comment]
Same issue, changed ownership of proxy and signaling files, upgrade go, resinstall all from scratch on another server : nothing change .. Don't understand what I'm doing wrong .. Even with all my firewall rules bypassed or with allow = all option, I have every time the same error. 

And the json given seems to have a correct format (in logs, don't when it's "unmarshalled") ..

PHP : 8.2
Web server : Nginx 1.22.1
BDD : 10.11.4
Janus : 0.14.1
USRSCTP : 0.9.5.0
Nats : 2.2.1

Until the 28.0.2 Nextcloud version all was ok but with oldest signaling, nats, janus and usrsctp version and with another high backend server that have the old version, all is ok (without sip dial-out protocol cause it's unsupported with it).

**Comment by fancycode** [comment]
Please check if the solution from #180 (run `make clean` before building) resolves the issue for you.

**Comment by SaadYasir** [comment]
make clean works for me

**Comment by Simthem** [comment]
Oh ok !! So sorry, I did not find this issue :/ sorry for the disturb and thanks a lot ! :)

**Comment by fancycode** [comment]
Ok, closing then.
