### ISSUE TITLE
Apache proxy

### ISSUE THREAD

**Issue by Byter3** [strukturag/nextcloud-spreed-signaling#66]
Hi!

I set up the signaling server on a different VM. My webfacing VM runs nextcloud on an Univention appliance.
I SSH-d in to that VM an made a singaling.conf for proxying to the signaling server as it writen down here in the readme.

But I only get a 404. I made some tweeks, I created a different DNS name for it and used it in th proxy conf as servername, now I get a 503 in the nextcloud talk settings, I even managed to reach the internal nginx server of the signaling VM. But something still doesn't add up.

Some help would be much appreciated!
Thanks!

**Comment by fancycode** [comment]
Is this related to #82?

**Comment by fancycode** [comment]
Assuming this was resolved with the change in #82, feel free to reopen with more details if this still happens.
