### ISSUE TITLE
Issue when throttling requests

### ISSUE THREAD

**Issue by SystemKeeper** [strukturag/nextcloud-spreed-signaling#763]
Noticed while analysing logs:

> Jun 18 15:48:24 s4 nextcloud-spreed-signaling[2508691]: throttle.go:279: Failed attempt on "HelloResume" from \<IP>, throttling by -2481983h47m40.703064064s

This does not look right, but might be just a log issue?

Other entries look fine though:

> Jun 18 15:30:48 s4 nextcloud-spreed-signaling[2508691]: throttle.go:279: Failed attempt on "HelloResume" from \<IP>, throttling by 25s

**Comment by fancycode** [comment]
An overflow could happen when calculating the delay to throttle if too many requests failed in a short time. Thanks for spotting this.
