### ISSUE TITLE
Signaling answers “404 page not found”

### ISSUE THREAD

**Issue by UspAN** [strukturag/nextcloud-spreed-signaling#77]
Hello.
I installed Signaling server as it described [here](https://markus-blog.de/index.php/2020/07/30/how-to-install-nextcloud-talk-high-performance-backend-with-stun-turnserver-on-ubuntu/). Everything is OK, in syslog I have:
_Jan 21 13:20:28 nc-talk-srv systemd[1]: Started Nextcloud Talk signaling server.
Jan 21 13:20:28 nc-talk-srv signaling[14053]: main.go:130: Starting up version 25b2722a4cb039acf2ad8edfedefe433b4a21439/go1.15.6 as pid 14053
Jan 21 13:20:28 nc-talk-srv signaling[14053]: main.go:139: Using a maximum of 4 CPUs
Jan 21 13:20:28 nc-talk-srv signaling[14053]: natsclient.go:116: Connection established to nats://localhost:4222 (NDKXRAPVENPIW3QZWOFVPIF7FKXQUU7EXGE3J3CLLJYBWXVD72S7DCLF)
Jan 21 13:20:28 nc-talk-srv signaling[14053]: hub.go:165: WARNING: No shared secret has been set for internal clients.
Jan 21 13:20:28 nc-talk-srv signaling[14053]: backend_configuration.go:77: Backend backend-1 added for https://nextcloud.my-domain.tld/
Jan 21 13:20:28 nc-talk-srv signaling[14053]: hub.go:177: Using a maximum of 8 concurrent backend connections per host
Jan 21 13:20:28 nc-talk-srv signaling[14053]: hub.go:184: Using a timeout of 10s for backend connections
Jan 21 13:20:28 nc-talk-srv signaling[14053]: hub.go:270: Not using GeoIP database
Jan 21 13:20:28 nc-talk-srv signaling[14053]: mcu_janus.go:289: Connected to Janus WebRTC Server 0.7.3 by Meetecho s.r.l.
Jan 21 13:20:28 nc-talk-srv signaling[14053]: mcu_janus.go:293: Found JANUS VideoRoom plugin 0.0.9 by Meetecho s.r.l.
Jan 21 13:20:28 nc-talk-srv signaling[14053]: mcu_janus.go:299: Data channels are supported
Jan 21 13:20:28 nc-talk-srv janus[697]: Creating new session: 5204023035686044; 0x7f9014004c30
Jan 21 13:20:28 nc-talk-srv signaling[14053]: mcu_janus.go:305: Full-Trickle is enabled
Jan 21 13:20:28 nc-talk-srv signaling[14053]: mcu_janus.go:308: Maximum bandwidth 1048576 bits/sec per publishing stream
Jan 21 13:20:28 nc-talk-srv signaling[14053]: mcu_janus.go:309: Maximum bandwidth 2097152 bits/sec per screensharing stream
Jan 21 13:20:28 nc-talk-srv janus[697]: Creating new handle in session 5204023035686044: 4705766480014858; 0x7f9014004c30 0x7f9014009d00
Jan 21 13:20:28 nc-talk-srv signaling[14053]: mcu_janus.go:315: Created Janus session 5204023035686044
Jan 21 13:20:28 nc-talk-srv signaling[14053]: mcu_janus.go:322: Created Janus handle 4705766480014858
Jan 21 13:20:28 nc-talk-srv signaling[14053]: main.go:226: Using janus MCU
Jan 21 13:20:28 nc-talk-srv signaling[14053]: hub.go:357: Using a timeout of 10s for MCU requests
Jan 21 13:20:28 nc-talk-srv signaling[14053]: backend_server.go:94: Using configured TURN API key
Jan 21 13:20:28 nc-talk-srv signaling[14053]: backend_server.go:95: Using configured shared TURN secret
Jan 21 13:20:28 nc-talk-srv signaling[14053]: backend_server.go:97: Adding "turn:turn.my-domain.tld:3478?transport=udp" as TURN server
Jan 21 13:20:28 nc-talk-srv signaling[14053]: backend_server.go:97: Adding "turn:turn.my-domain.tld:3478?transport=tcp" as TURN server
Jan 21 13:20:28 nc-talk-srv signaling[14053]: backend_server.go:104: No IPs configured for the stats endpoint, only allowing access from 127.0.0.1
Jan 21 13:20:28 nc-talk-srv signaling[14053]: main.go:302: Listening on 127.0.0.1:8080_
but at the end of step 5 when I try
`curl -i http://127.0.0.1:8080/standalone-signaling/api/v1/welcome`
I recieve an answer:
```
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 19 Jan 2021 10:48:25 GMT
Content-Length: 19
```
What could be the reason?

**Comment by fancycode** [comment]
The signaling server listens directly in the root, e.g. `curl -i http://127.0.0.1:8080/api/v1/welcome` should work. 

The path `/standalone-signaling` is usually handled by a frontend webserver as described in the README.md:
https://github.com/strukturag/nextcloud-spreed-signaling#setup-of-frontend-webserver
