### ISSUE TITLE
[Question] Is it mandatory to use https for signaling server 

### ISSUE THREAD

**Issue by elhananjair** [strukturag/nextcloud-spreed-signaling#771]
Hello there, 
I am trying to set up a signaling server for the Nextcloud Talk application, and so far I have successfully installed 
  - Janus
  - Turn
  - NATS server and 
  - Signal Server (this repo)

Here is what I have done in detail and what I am facing...
I have installed `coturn` package from the Fedora package manager. I have installed `certbot` and retrieved two certificates from Letsencrypt
   1. for turn (https://coturn.mydomain.dev)
   2. for signal (https://signal.mydomain.dev) 
   
   They look like this:
   
![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/69236638/78b7a359-a383-43f8-aec7-d8e8a975e3c3)

Turn server is working fine testing from nextcloud
![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/69236638/bfbbb07f-d869-4502-a9ae-b6dbee285466)

But in the High-performance backend, I am getting an error when **Validate SSL Certificate** is ticked 

![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/69236638/199802dc-b559-4ca3-b7ca-f7f99f542c56)

If  **Validate SSL Certificate** is not ticked, it doesn't show an error but the **talk application doesn't work**.
![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/69236638/75b575fb-ac40-4b04-85de-a919aefb0f46)

Here is logs from **httpd** and **Nextcloud**

**HTTP (Apache) log from signal server**
**httpd error_log**

```
[Thu Jul 04 16:13:56.840309 2024] [suexec:notice] [pid 202755:tid 202755] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Jul 04 16:13:56.849898 2024] [ssl:warn] [pid 202755:tid 202755] AH01909: signaling.acso.gov.et:443:0 server certificate does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fe80::226:b9ff:fe47:4e16%eno1. Set the 'ServerName' directive globally to suppress this message
[Thu Jul 04 16:13:56.890189 2024] [ssl:warn] [pid 202755:tid 202755] AH01909: signaling.acso.gov.et:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 04 16:13:56.891813 2024] [lbmethod_heartbeat:notice] [pid 202755:tid 202755] AH02282: No slotmem from mod_heartmonitor
[Thu Jul 04 16:13:56.893739 2024] [systemd:notice] [pid 202755:tid 202755] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu Jul 04 16:13:56.899580 2024] [mpm_event:notice] [pid 202755:tid 202755] AH00489: Apache/2.4.59 (Fedora Linux) OpenSSL/3.1.1 configured -- resuming normal operations
[Thu Jul 04 16:13:56.899624 2024] [core:notice] [pid 202755:tid 202755] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Jul 04 16:16:59.638989 2024] [autoindex:error] [pid 202761:tid 202863] [client 71.6.134.231:59514] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive

```
**httpd ssl error_log**
```
[Thu Jul 04 16:13:56.847126 2024] [ssl:warn] [pid 202755:tid 202755] AH01909: fe80::226:b9ff:fe47:4e16%eno1:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 04 16:13:56.887609 2024] [ssl:warn] [pid 202755:tid 202755] AH01909: fe80::226:b9ff:fe47:4e16%eno1:443:0 server certificate does NOT include an ID which matches the server name

```
**Web browser log**
![image](https://github.com/strukturag/nextcloud-spreed-signaling/assets/69236638/fecaf5f5-06fd-4f3b-8aa6-6d00cd0e2860)

Does creating two certificates for turn and signal server cause this issue?

**Comment by fancycode** [comment]
Please make sure that accessing `https://signaling.XXX/` and `https://coturn.XXX:5349/` uses the correct certificate for the hostname. You can check this in the browser or with tools like `curl` or `openssl s_client`.

In any case this is not an issue of the signaling server but more a topic for the community forum at https://help.nextcloud.com/c/support/talk/52

**Comment by elhananjair** [comment]
Hello @fancycode 
Thank you so much, yes you were right, the problem was the certificates, I changed a command I used to retrieve the certificates and it's working now. 

But can you support me on another related issue, please 

I am using Fedora Server, and for now, I changed SELinux status to permissive, otherwise signal server won't work, I couldn't find documentation on how to deal with it on this repo. 

Secondly, I have two instances of Nextcloud and the signal server works fine for Nextcloud version 27, but for Nextcloud Version 29 instance, I am getting the following error

```
ClientException Client error: `POST https://signaling.mydomain.tld/standalone-signaling/api/v1/room/j5knkv9k` resulted in a `429 Too Many Requests` response: Too many requests
Failed to send message to signaling server 
```
and here is a log from `signaling.service` file

```
throttle.go:279: Failed attempt on "BackendRoomAuth" from Nextcloud Version 29 Instance public IP, throttling by -810335h10m58.629238784s
```

**Comment by elhananjair** [comment]
> Hello @fancycode Thank you so much, yes you were right, the problem was the certificates, I changed a command I used to retrieve the certificates and it's working now.
> 
> But can you support me on another related issue, please
> 
> I am using Fedora Server, and for now, I changed SELinux status to permissive, otherwise signal server won't work, I couldn't find documentation on how to deal with it on this repo.
> 
> Secondly, I have two instances of Nextcloud and the signal server works fine for Nextcloud version 27, but for Nextcloud Version 29 instance, I am getting the following error
> 
> ```
> ClientException Client error: `POST https://signaling.mydomain.tld/standalone-signaling/api/v1/room/j5knkv9k` resulted in a `429 Too Many Requests` response: Too many requests
> Failed to send message to signaling server 
> ```
> 
> and here is a log from `signaling.service` file
> 
> ```
> throttle.go:279: Failed attempt on "BackendRoomAuth" from Nextcloud Version 29 Instance public IP, throttling by -810335h10m58.629238784s
> ```

Never mind, the second issue was because of the configuration issue, I didn't add the domain to `[backend]` section. 
But the SELinux thing, is there a way to allow signal server?
