### ISSUE TITLE
SELinux blocking signal server

### ISSUE THREAD

**Issue by elhananjair** [strukturag/nextcloud-spreed-signaling#772]
Hello @fancycode 
signal server was working fine without a problem on old versions, but now SELinux is blocking it, for now, I am setting it to be 'permissive', I couldn't find a topic on this while reading the documentation on setting up a signal server.

**Comment by fancycode** [comment]
Could this be the same as #322 / #615? You should see the actual SELinux blocking event in one of the logfiles which should point you to the syscall that was blocked.

**Comment by elhananjair** [comment]
Thank you @fancycode 

I fixed it using the following command
`setsebool -P httpd_can_network_connect on`
