### ISSUE TITLE
Add the ability to configure supported codecs and profiles

### ISSUE THREAD

**Issue by Ivansss** [strukturag/nextcloud-spreed-signaling#79]
There should be a way to configure supported codecs and profiles.
At the moment Janus forces VP8 as the only video codec to use:
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2306

**Comment by Gymnae** [comment]
Created an upstream issue, which might help: 
https://github.com/meetecho/janus-gateway/issues/3205
