### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by htc1977** [strukturag/nextcloud-spreed-signaling#8]
Hi,

after compiling, installing and configuring the signaling server on a new Ubuntu 20.04 I get this error message in the logs, when I try to initiate a Talk call.

`2020/05/20 11:19:02.412062 backend_client.go:345: Could not send request {"type":"auth","auth":{"version":"1.0","params":{"userid":"[USER]","ticket":"UP***********kI:1589973319:[USER]:d9f4*******************************************************************739"}}} to https://nextcloud.domain.reg/ocs/v2.php/apps/spreed/api/v1/signaling/backend: context deadline exceeded
`

Nextcloud version is 18.0.4 and Talk had been upgraded to the latest 8.0.9.

The benchmark client connects without any issues via localhost on the same machine.

**Comment by fancycode** [comment]
Can the server that runs the signaling server access `https://nextcloud.domain.reg/ocs/v2.php/apps/spreed/api/v1/signaling/backend`? The timeout is 10 seconds by default and configured at https://github.com/strukturag/nextcloud-spreed-signaling/blob/5dcfeda1e9edd7076b71e052e67ea086c0a7460f/server.conf.in#L61

**Comment by htc1977** [comment]
you were so right ... there was an issue with the name server.
Sorry. My fault!

Thank you very much.
