### ISSUE TITLE
LXC Support

### ISSUE THREAD

**Issue by grickard** [strukturag/nextcloud-spreed-signaling#81]
Hello,

I realize this is probably going to be a non-priority but I figured I'd throw it out there. Would it be possible to add support for unprivileged LXC containers? I have a "functioning" container built, however Talk is silently failing (just spins and never connects), even with everything set to debug. Janus and NATS are running without issue. I can provide any node or container logs that might be needed.

Thanks!

**Comment by XueSheng-GIT** [comment]
Can you provide further details on your setup?
I'm using unprivileged LXC for signaling without any issues (Ubuntu 20.04 LXC on Proxmox VE6).

**Comment by grickard** [comment]
Proxmox VE6
Ubuntu 18.04 LXC
Single net interface configured directly with a dedicated public IP.
Nesting Enabled

I followed the exact same installation steps I took to get it successfully working on a KVM machine. The problem I ran into was a silent failure. Everything would start-up and be functioning just fine. I'd even get the "OK" status in the NC talk settings. However when I attempted to start a call, it would never start and simply sit there and spin.

That's really interesting you got it up and running. Did you follow any particular guide?

**Comment by XueSheng-GIT** [comment]
Did you try LXC privileged in comparison too (instead of KVM)? What about syslog? No errors? 

I had a look at different guides and picked out the matching parts (none seemed to be fitting completely ;)).

**Comment by XueSheng-GIT** [comment]
@grickard does your LXC container have its own, public ip or do you use a local ip behind nat?
While testing I noticed that janus behind nat only makes trouble. Since using a dedicated, public ip for the signaling server, everything seems to run fine.

**Comment by fancycode** [comment]
This sounds more like a configuration issue of LXC than a problem in the signaling server. Feel free to reopen with more details what needs to be changed in the signaling server.
