### ISSUE TITLE
Help in docker compose  add backend server HBP

### ISSUE THREAD

**Issue by felipesms** [strukturag/nextcloud-spreed-signaling#819]
My docker compose is ok, in my lan network is ok too,but now i want add backend server -  record videos

nextcloud server  192.168.3.100

compose
----------------------------------------------------------------------------------------------------------------
networks:
  nextcloud:

services:
  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always
    networks:
      - nextcloud
    expose:
      - 6379

  nextcloud_postgresql: 
    image: postgres:15
    container_name: nextcloud_postgresql
    restart: always
    volumes:
      - ./srv/postgresql:/var/lib/postgresql/data
    networks:
      - nextcloud
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=lovelove

  nextcloud:
    image: nextcloud:28.0.4-fpm
       
    container_name: nextcloud

    volumes:
      - ./srv/nextcloud/apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - /home/felipe/disco/nextcloud/dados:/var/www/html/data
      - ./srv/nextcloud/html:/var/www/html
      - ./ssl:/etc/nginx/ssl
      - /etc/localtime:/etc/localtime:ro

    networks:
      - nextcloud
    environment:
      - TZ=America/Sao_Paulo
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.3.100
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - REDIS_HOST=nextcloud_redis

      - POSTGRES_HOST=nextcloud_postgresql
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=p3r3r3c4

      - PHP_MEMORY_LIMIT=10000M
      - PHP_UPLOAD_LIMIT=10000M

      - SMTP_HOST=smtp.meudominio.com.br
      - SMTP_PORT=587
      - SMTP_AUTHTYPE=LOGIN
      - SMTP_NAME=cloud@meudominio.com.br
      - SMTP_PASSWORD=senhacontaemail
      - MAIL_FROM_ADDRESS=cloud
      - MAIL_DOMAIN=meudominio.com.br
    command: >
      /bin/sh -c "
        apt-get update && apt-get install -y ffmpeg && php-fpm"

  nextcloud_web:
    container_name: nextcloud_web
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/http.conf:/etc/nginx/conf.d/http.conf
      - ./nginx/nextcloud.conf:/etc/nginx/conf.d/nextcloud.conf
      - ./srv/nextcloud/html:/var/www/html:ro 
      - ./srv/nextcloud/apps:/var/www/html/custom_apps:ro      
      - ./ssl:/etc/nginx/ssl
    networks:
      - nextcloud
    ports:
      - 80:80
      - 443:443

**Comment by fancycode** [comment]
See https://github.com/nextcloud/nextcloud-talk-recording for the recording server for Nextcloud Talk.
