### ISSUE TITLE
High Performance Backend out of date

### ISSUE THREAD

**Issue by jared2876** [strukturag/nextcloud-spreed-signaling#828]
Getting the error that in Nextcloud that the high performance back end is out of date. 
This was noticed only after updating from Nextcloud 29 to Nextcloud 30. No other changes to the Nextcloud.
![Screenshot from 2024-10-01 18-18-24](https://github.com/user-attachments/assets/ab916dd8-a8a4-4ed5-9dd7-f6fb311f81d1)
The installation of the signaling server is in a docker container installed by a script. The script points to the Master file of this git.

I am willing to concede to this being user issue.

**Comment by fancycode** [comment]
Commit 2e8b0dfe25d746871535078a96bc616a72ecc4da is rather old. Please consider switching to the offical Docker images or upgrade your image to [v2.0.0](https://github.com/strukturag/nextcloud-spreed-signaling/releases/tag/v2.0.0).
