### ISSUE TITLE
Problem starting 2.0.1 docker

### ISSUE THREAD

**Issue by muchachagrande** [strukturag/nextcloud-spreed-signaling#855]
Hi,

I've updated 2.0.0 to 2.0.1 docker and it doesn't start.
The log says:

>Preparing signaling server configuration in /config/server.conf ...
>cp: can't create '/config/server.conf': Permission denied

**Comment by fancycode** [comment]
Please provide your complete command how you are starting the signaling server in Docker. Are you mounting volumes?
