### ISSUE TITLE
How to use without a (public) coturn server

### ISSUE THREAD

**Issue by tunnelpr0** [strukturag/nextcloud-spreed-signaling#87]
As given in the documentation and in the examples here, it is required to have a public coturn server for running the signaling server. I also tested this and its really required.

But i also ordered the test version of the official high perfomance backend, which worked perfect without any TURN/STUN server.

So may you can explain to me, how i have to set up the signaling server, that there is no need of a public coturn server?

Thanks!

**Comment by fancycode** [comment]
A coturn server is only required if Janus is not reachable directly by the clients, e.g. if they are beind a firewall / NAT that blocks direct connections. Also this is independent of the signaling server and the STUN / TURN server must be configured in Nextcloud Talk.
