### ISSUE TITLE
Janus MCU data channels not supported - do I have a wrong URL?

### ISSUE THREAD

**Issue by htc1977** [strukturag/nextcloud-spreed-signaling#9]
Hello,

I've successfully managed to compile everything, but where do I find how a mcu url looks like, which I need to configure here? 
`Edit the server.conf and enter the URL to the websocket endpoint of Janus in the section [mcu] and key url. During startup, the signaling server will connect to Janus and log information of the gateway.`

Thanks in advanced, Christian.

**Comment by htc1977** [comment]
it looks like the URL needs to be like:
`ws://localhost:8188`
but I receive an error with not supported data channels
```
2020/05/22 08:26:48.421385 mcu_janus.go:279: Connected to Janus WebRTC Server 0.10.0 by Meetecho s.r.l.
2020/05/22 08:26:48.421444 mcu_janus.go:283: Found JANUS VideoRoom plugin 0.0.9 by Meetecho s.r.l.
2020/05/22 08:26:48.421486 main.go:175: Could not create janus MCU at ws://localhost:8188: Data channels are not supported
2020/05/22 08:26:48.421521 main.go:182: Could not initialize janus MCU at ws://localhost:8188 (Data channels are not supported) will retry in 1s
2020/05/22 08:26:49.423718 mcu_janus.go:279: Connected to Janus WebRTC Server 0.10.0 by Meetecho s.r.l.
2020/05/22 08:26:49.424061 mcu_janus.go:283: Found JANUS VideoRoom plugin 0.0.9 by Meetecho s.r.l.
2020/05/22 08:26:49.424316 main.go:175: Could not create janus MCU at ws://localhost:8188: Data channels are not supported
2020/05/22 08:26:49.424555 main.go:182: Could not initialize janus MCU at ws://localhost:8188 (Data channels are not supported) will retry in 2s
```

**Comment by Dark-Schnitzel** [comment]
Hi htc1977,
i got this in my server.conf:
`[mcu]
# The type of the MCU to use. Currently only "janus" is supported.
type = janus

# The URL to the websocket endpoint of the MCU server. Leave empty to disable
# MCU functionality.
url = ws://localhost:8188/janus
`

**Comment by fancycode** [comment]
Janus must be built with support for Data Channels, see https://github.com/meetecho/janus-gateway#dependencies for necessary dependencies.

**Comment by htc1977** [comment]
thank you @Dark-Schnitzel and @fancycode 
I forgot this:
`For what concerns usrsctp, which is needed for Data Channels support, it is usually not available in repositories, so if you're interested in them (support is optional) you'll have to install it manually. It is a pretty easy and standard process:`

damn...

**Comment by morph027** [comment]
For anyone else stumbling upon this:
I've built backports of recent janus versions for at least Ubuntu Bionic and Focal: https://gitlab.com/packaging/janus

**Comment by elhananjair** [comment]
> thank you @Dark-Schnitzel and @fancycode I forgot this: `For what concerns usrsctp, which is needed for Data Channels support, it is usually not available in repositories, so if you're interested in them (support is optional) you'll have to install it manually. It is a pretty easy and standard process:`
> 
> damn...

hello @htc1977 
I am encountering the same issue here, I have already installed data channel before building janus on my Fedora Server:
> Package usrsctp-devel-1:0.9.5.0-4.fc36.x86_64 is already installed.

This is the output from signalling server:
```
main.go:193: Could not create janus MCU: Data channels are not supported
main.go:200: Could not initialize janus MCU (Data channels are not supported) will retry in 1s
mcu_janus.go:294: Connected to Janus WebRTC Server 1.0.3 by Meetecho s.r.l.
mcu_janus.go:300: Found JANUS VideoRoom plugin 0.0.9 by Meetecho s.r.l.
main.go:193: Could not create janus MCU: Data channels are not supported

```
